src/lib/watch.coffee

Corrige o watch para usar o .vtexignore devidamente.
Após detectado o bug, percebi que o watch estava olhando pra a pasta root inteira do projeto, e não somente para os arquivos já filtrados anteriormente pelo listFile() (função que devolve os arquivos para observar e o que ignorar). 
Isso faz com que qualquer mudança na pasta do projeto ignore o que é definido em .vtexignore. Então, a solução proposta é fazer o watch "olhar" apenas os arquivos já filtrados.
**EDIT**
Agora olha para o root e ignora de acordo no ignored do watcher!
Está funcional mas creio que pode ser refinado, irei trabalhar isso conforme faço o teste.

Corrige o watch para usar o .vtexignore

---

src/lib/file-manager.coffee
src/lib/watch.coffee

Fix #33 
Add the possibility of creating a .vtexrc file on the root path of your project to define custom request configs.
For now, only the endpoint and accept header can be customized:
GalleryEndpoint = "your_endpoint"
AcceptHeader = "your_accept_header"
You can comment the lines by prepending them with     #:

Add vtexrc for custom request

---

src/lib/auth.coffee

Change login prompt messages from this:
```
> account
> email
> password (typing will be hidden)
```
To:
```
> account name of the store you are developing
> email
> password (typing will be hidden)
```

Change prompt message to a more meaningful one

---

package.json
src/lib/auth/credentials.js
src/lib/auth/login.js
src/lib/publish.js
src/lib/watch.js

Fixes https://github.com/vtex/toolbelt/issues/90
@tamorim can you take this branch for a spin?
From https://github.com/FGRibreau/node-request-retry
> When the connection fails with one of ECONNRESET, ENOTFOUND, ESOCKETTIMEDOUT, ETIMEDOUT, ECONNREFUSED, EHOSTUNREACH, EPIPE, EAI_AGAIN or when an HTTP 5xx error occurrs, the request will automatically be re-attempted as these are often recoverable errors and will go away on retry.
```
// The below parameters are specific to request-retry
maxAttempts: 5,   // (default) try 5 times
retryDelay: 5000,  // (default) wait for 5s before trying again
```

Use request wrapper with retry capability

---

src/workspace.js
src/workspace.test.js

Update the link shown to the user during the watch command.
The query string key changed to `vtex_workspace` to match the cookie name. Also, we're publishing the new render only in `alpha` right now.
`vtex watch`, see the new link is issued.

Fix vtex workspace link

---

README.md
scripts/prompt.bash

Adds account and workspace labels to bash prompt
You must source the file `scripts/prompt.bash`

Adds basic account and workspace labels to bash prompt

---

src/file.js

Add support to watching any JSON file at root level.
Only `manifest.json` was watched at root level. The router needs, for instance, `routes.json`.
* Add `bla.json` to root
* Start watch
* Change file
* Verify that the change has been applied

Support watching any JSON file at root level

---

src/file.js
src/modules/apps.js

Make our `.vtexignore` behave more similarly to `.gitignore`.
Because the way `node-glob` works, if you list `src/` in your `.vtexignore` all files inside will still be matched. To ignore everything, you need to actually force `src/**`. This adds stars automatically.
This is not the optimal solution, as we should conform to the actual [spec](https://git-scm.com/docs/gitignore), or maybe use something like https://github.com/kaelzhang/node-ignore, but it improves the experience for now.
Ignore a folder using `/` at the end, watch things not get sent.
N/A

Automatically add glob stars to folders in vtexignore

---

src/modules/workspace.js

Make `vtex workspace reset` argument optional and add a retry for slow workspace deletion.
Usage of the reset command.
Using `vtex workspace reset` with and without an argument and ensuring everything works.
n/a

Improve the workspace reset command

---

src/file.js

Prevent empty files from being sent to apps/vbase.
Resource not found when trying to get an empty file on vbase.
Trying to send any empty files during the watch startup or via changes.
n/a

Filter empty files on watch

---

package.json
src/modules/apps/install.js
src/modules/apps/list.js
src/modules/apps/settings/index.js
src/modules/apps/uninstall.js
src/modules/workspace/delete.js
src/modules/workspace/reset.js

To allow `install` and `uninstall` with multiple apps and make `uninstall` require an optional argument!
If you run `vtex uninstall` it will uninstall the app on the current folder.
Not having to type a lot to install or uninstall stuff :smile:  
Try to install and uninstall more than one app.
`vtex install vtex.shelf@0.5.3 vtex.react-slick@0.15.3`
`vtex uninstall vtex.shelf vtex.react-slick`

Allow batch install and uninstall (and uninstall without args)

---

src/courier.js
src/locator.js
src/modules/apps/install.js
src/modules/apps/uninstall.js
src/modules/workspace/delete.js
src/modules/workspace/reset.js
src/spinner.js
src/terminal.js

When you install or uninstall an app the VTEX Apps response is just a part of what actually happens on the background.
If you install a render app, for example, after the VTEX Apps response the render service still have to pick up the installed app and build a bundle with it.
If you install and switch directly to the page, you won't see what you wanted because render is still working it's magic.
This PR aims to fix that by adding loaders and connecting with the courier service to receive the messages that other systems may pass when working with the install or uninstall of an app.
install/uninstall commands being too simple on it's success.
Just try to install or uninstall any app on your workspace :smiley: 
n/a

Add loaders for install and uninstall commands

---

package.json
src/locator.js
src/manifest.js
src/manifest.test.js
src/modules/apps/install.js
src/modules/apps/publish.js
src/modules/apps/utils.js
src/modules/apps/watch.js

To adapt the toolbelt to a breaking change in the apps server related to publishing and installing apps.
The apps server has unified the registry so that it is no longer separated by workspace. This required a change to the way watched apps are updated. Now, instead of saying `isDevelopment`, a special tag is passed, in the format `dev.<workspace-name>`. Oh yes, versiontags are now supported, in the lines of NPM's `dist-tag`s :)
1. Prepare to use the beta environment
* point the apps endpoint to beta
* link the `@vtex/api` package to use `feature/install-prototype` branch, which has a PR open (vtex/node-vtex-api#13)
2. Run `vtex watch` and see if everything works as expected
3. Publish an app with `vtex publish --tag foo`
4. Install the app with `vtex install my.app@foo`, and verify that …

Support registry with unified workspace

---

src/cli.js
src/modules/auth/index.js
src/modules/auth/switch.js

Add a `switch` command to change between accounts.
Boring process of logging again every time a user wants to change the current account. 
Use `vtex switch <account>`
n/a

Add switch command for switching between accounts

---

package.json
src/update.js
yarn.lock

Fix the behavior of the `update-notifier` package.
Now the messages won't lag behind and they're displayed when you exit the CLI.
Fix the behavior of the `update-notifier` package that kind of  "lagged" the version checks.
Link this branch and play with the `package.json` version and run any `vtex` command.
n/a

Fix update-notifier lag

---

package.json
src/manifest.js
src/modules/apps/add.js
src/modules/apps/index.js

Add the `vtex add` command.
It adds the desired VTEX app or npm package as a dependency to your `manifest.json` file.
If you use without providing a version, then the latest version for that app/package will be fetched and added with a fixed major version (so you get minors and patches automatically, a la npm default). 
Boring and cumbersome addition of dependencies on your app.
Use `vtex add` with any app or npm package inside a app directory containing a `manifest.json` file.
Hint: It supports multiple arguments!
n/a

Add `vtex add` command

---

src/courier.js
src/modules/apps/link.js

To add the sender to logged messages. If the sender is the linked app itself, the sender is omitted.
Sometimes, especially when using GraphQL calls, it is really hard to tell where logged messages are coming from. This makes it more explicit.
Run `vtex link`. You should see the sender for each message.

Appends sender to logged messages

---

src/courier.js

Fix a bug that happens when an error with no message is logged.
Today my app received an error with no message, and so toolbelt failed when trying to log it, saying: `TypeError: Cannot read property 'replace' of undefined`.
It's bad to have errors without messages, but I've added a check so that toolbelt at least won't fail when that happens, and we can ask for more error details in these cases as we detect them.
Send an error with no message and check that toolbelt doesn't fail.
n/a

Fix logging of error with no message

---

src/clients.ts
src/courier.ts
src/modules/apps/link.ts
src/modules/workspace/index.ts
src/modules/workspace/prepare.ts
typings.d.ts

Add a new command to prepare workspace for production
Currently there is no way to trigger a production build on render-builder and set a workspace as "stable"
Use the `vtex workspace prepare` command while linking render-builder using the branch feature/production

Create command to prepare workspace for production

---

.eslintrc

Prevent misleading eslint warning about external imports.
Eslint warning for stuff like:
```javascript
import React from 'react'
```
or
```javascript
import Link from 'vtex.render-runtime/components/Link'
```
Run `vtex setup eslint` on an app folder and try one of the imports mentioned before.
Check your editor warnings or run the eslint bin to check for the project.
n/a

Improve unresolved regex to only match packages

---

.travis.yml
package.json
src/modules/apps/link.ts
src/modules/apps/publish.ts
src/modules/apps/utils.ts

This commit adds support for VTEX/builder-hub messages, replacing
the `toggle` routes.
Check https://github.com/vtex/builder-hub/pull/280 for more information.

Add support for builder-hub messages

---

package.json
src/modules/apps/publish.ts

This commit changes toolbelt's behaviour whenever a `publish` command fails:
- Stop throwing 'Something exploded'.
- Reduce the amount of error messages that appear.

Handle error when publish fails

---

package.json
src/modules/apps/deprecate.ts
src/modules/apps/undeprecate.ts
src/modules/apps/utils.ts
src/modules/tree.ts

Used to revert deprecation of apps. The usage is exactly the same as the `vtex deprecate` command.
The code is also almost the same as the 'deprecate.ts' module, except that we need to manually implement a http request, because `node-vtex-api` does not expose any method for undeprecating apps.
In the near future we will implement an `undeprecateApp` method in `node-vtex-api`, upgrade the version of `node-vtex-api` used in this project and use it instead of the `axios` http request.

Implement `vtex undeprecate`

---

src/cli.ts

Do a simple check on the expiration of local token when using the cli.
Saves people some time since the local token will always be valid (if it is not valid, it will immediately prompt for login).
Run 'vtex local token' with an expired token configured.

Validate expiration of token in checkLogin

---

package.json
src/modules/apps/link.ts
src/modules/apps/update.ts
src/modules/apps/utils.ts
src/modules/tree.ts
src/typings/global.d.ts
yarn.lock

This commit affects the `vtex link` command in the following way:
- In the beginning of the linking process, checks for app dependencies in
manifest.json. These dependencies are then added to react/package.json as
`devDependencies`, pointing to endpoints in vtex.asset-server (https://github.com/vtex/asset-server/pull/12).
- Also asks vtex.builder-hub if it injects any dependencies in this app. vtex.builder-hub answer contains only dependencies that export components that the user is supposed to use in his app (only render-runtime, for the time being).
- `yarn --force` is run in the `react` folder, in order to fetch typings and
install other dependencies.
The above procedures are carried out once for each `vtex link`.
- Clone asset-server (vtex/asset-server#12). Link it with `vtex link`.
- …

Fetch typings for react apps

---

package.json
src/modules/apps/link.ts

This PR attempts to fix the issue the error when running `yarn` for the `vtex link --install` command. Also adds some convenient error handling and updates the routes for typings fetching from vtex/asset-server.

Fix yarn running in vtex link --install

---

package.json
src/modules/init/git.ts
src/modules/init/index.ts

This PR proposes 2 modifications in the `vtex init` command:
- Leave only `dreamstore` (vtex-apps/dreamstore)  as starting template.
- Instead of deleting everything in the current working folder, create a new folder with the template's content.

Improve init behaviour and remove bad templates

---

package.json
src/modules/apps/link.ts
src/modules/apps/undeprecate.ts

This PR changes the route of the typingsInfo call to builder-hub, reflecting the changes made in #vtex/builder-hub/pull/340.

Fix call to builder-hub's typingsInfo route

---

package.json
src/cli.ts

Add `config` to whitelist of commands that don't need a valid credential to run.
Config must be in this whitelist so the environment can be changed even when it is not working.
Build and try to change environment with an expired/non-existent token.

Add config to whitelist

---

CHANGELOG.md
package.json
src/manifest.ts
src/modules/apps/add.ts
src/modules/apps/link.ts
src/modules/init/index.ts

Add possibility to link in any subdirectory of an app.
It was kind of annoying to go to the root of the app to be able to link.
- Generate a executable running `yarn build`
- Inside any app, go to a subdirectory and run `~/path/to/toolbelt/lib/cli.js link`

Enable linking in subdirectories

---

package.json
src/modules/browse/admin.ts
src/modules/tree.ts

To add a new set of commands: `vtex browse`. For now, it has `vtex browse admin`, but can be expanded.
Currently, it is a hassle to open admin pages when you're already on toolbelt. You need to craft the url yourself if it's your first time opening it, or search through your browser history to find the correct link. 
Now, if you're already on toolbelt, just by using `vtex browse admin`, the admin panel will open in your default browser.
- download this branch and `yarn watch` it.
- login to any account/workspace, in prod or staging. It should work everywhere.
- Use `vtex browse admin`, watch magic happen.

Adds command `vtex browse admin`

---

src/modules/workspace/abTest.ts
src/modules/workspace/production.ts

Most of the changes are error messages that suggest a better course of action to the users. More specifically, we should not suggest that a user simply unlinks all apps before moving a workspace to production. Although we cannot currently forbid it, this will not be allowed in the future and, because of that, we should encourage the users to either create a new workspace or reset the current one instead.
Another thing that is being fixed is that we should not skip the `vtex production` step for workspaces that are going to be put into A/B tests. The workflow for those should be the same as for promoting a workspace directly right until the last step, which is `vtex workspace test <weight>` instead of `vtex promote`, so users should run `vtex production` **before** that. This means …

Some fixes to workspace handling for production and AB test

---

src/modules/browse/admin.ts

To make `vtex browse admin` work directly on supported accounts.
`vtex support` is not very useful if there isn't a way to 
- `yarn watch` this branch.
- go to `vtexgame2/pedro823`.
- Do `vtex support vtexgame3`. You should now be in `vtexgame3`.
- Do `vtex use pedro823`.
- Do `vtex browse admin`. This should open the browser in the admin,
with the support cookie on `VtexIdClientAutCookie`.

Adds vtex browse admin on support accounts

---

package.json
src/modules/apps/unlink.ts

Adds a better error message whenever the user tries to unlink an app that is not linked in the current workspace.

Improve unlink error message when app is not found in the workspace

---

package.json
yarn.lock

This PR upgrades the `chokidar` version, attempting to solve an issue with the filesystem watcher during `vtex link`.
The issue has recently started happening with VSCode: whenever a file is saved, it is shown as Updated => Deleted => Updated in `vtex link` logs.

Upgrade chokidar version

---

CHANGELOG.md
package.json
src/modules/apps/link.ts
src/modules/tree.ts

As the title says, this PR implements an option for the `vtex link` command.
Issuing `vtex link --no-watch` will make the command exit as soon as the app has finished the linking process.

Implement --no-watch option for `vtex link`

---

CHANGELOG.md
package.json
src/modules/release/utils.ts

This PR fixes the following `vtex release` issue:
- Post release scripts output were not being correctly redirected to stdio.

Fix post release

---

CHANGELOG.md
package.json
src/modules/release/index.ts
src/modules/release/utils.ts

This PR makes `vtex release` update the `CHANGELOG.md` only on stable releases.

Update changelog only on stable releases

---

CHANGELOG.md
package.json
src/modules/apps/link.ts

This PR is an attempt to fix an issue with the file system watcher during the `vtex link`. There are reports that updated files are being first queued as deleted by the watcher. This makes builder-hub 'patch' the build removing the file, and the build fails.

Attempt to fix changed file issue

---

CHANGELOG.md
package.json
src/modules/apps/link.ts
src/modules/apps/publish.ts

This PR:
- Includes the file stream creation inside the retried functions, solving the stream errors appearing when the first try fails.
- Makes retries happen only when vtex.builder-hub responds with status code >= 500.

Fix retries for app linking and publishing

---

CHANGELOG.md
package.json
src/modules/apps/install.ts

Improve error messages for install errors
Current displaying of install error codes do not help users on how to proceed to fix them. The proposed fix addresses this problem by giving more complete error messages
1. In account `extensions`, create a new workspace;
2. Associate a user with a `VTEX IO no-buy` or a `VTEX IO no-install` profile in Account Management (License Manager);
3. Login in your workspace with the created user email;
4. Try to install `vtex.google-shopping`, you should receive the message correspondent to the associated profile.

 Add handling for billing app install codes and KR forbidden errors

---

CHANGELOG.md
package.json
src/modules/apps/update.ts
src/modules/apps/utils.ts
src/modules/infra/utils.ts
src/modules/tree.ts

This PR makes the `vtex update` command stop updating majors by default. If the user wants to update app majors, they must use `vtex update -m` or `vtex update --major`.
This also fixes the colors in the version diff table:

Stop updating app majors by default

---

CHANGELOG.md
package.json
src/conf.ts
src/modules/apps/publish.ts

This PR makes toolbelt save the current account/workspace config before switching accounts during a `vtex publish`, so that, if the user wishes to return to his previously logged account, the config is automatically reverted.
This means: no more authentication to return to previous account after running `vtex publish`.

Save config of current account before changing account for publishing

---

CHANGELOG.md
package.json
src/modules/tree.ts
src/modules/workspace/create.ts
src/modules/workspace/use.ts
yarn.lock

Upgrade to @vtex/api to newest version (^2.3.0).

Upgrade node vtex api

---

CHANGELOG.md
package.json
src/modules/apps/publish.ts

This PR solves the following problem:
- The answer to the prompt asking if the user wants to go to his previously logged account after publishing an app was not being correctly parsed.

Fix "switch to previous account" answer parsing

---

src/modules/apps/link.ts
src/modules/apps/undeprecate.ts
src/modules/browse/admin.ts
src/modules/infra/install.ts
src/modules/infra/update.ts
src/modules/workspace/create.ts

The goal is to move all region handling to a single place so we can easily change a region's name or add/remove regions at will.
We are going to need this kind of thing a lot now that we have dev clusters.
1. Create a workspace both in staging and in production.
2. Use `vtex browse admin` both in staging and in production.
3. Link an app both in staging and in production.
4. Install and update infra apps both in staging and in production.
5. Undeprecate an app.

Small refactoring to centralize region handling

---

README.md
src/modules/apps/link.ts
src/modules/apps/utils.ts
src/modules/tree.ts
src/modules/workspace/abTest.ts
src/modules/workspace/production.ts
src/modules/workspace/promote.ts
src/modules/workspace/reset.ts
src/modules/workspace/status.ts
src/modules/workspace/use.ts

We do not allow `dev` workspaces to become `production` workspaces and the
opposite is not something we should do either (`dev` and `production` are mostly
separate worlds).
This means that a workspace reset (re-create the workspace
from scratch) should be allowed to create the workspace as any of those, but
`vtex production` no longer exists, neither with `true` nor with `false` as the
last argument. To phase out the command, first mark it as deprecated in the list
shown by `vtex help` and replace the actual command with an error message with
instructions.
Another consequence is that links are not allowed in a production workspace.
This change should avoid that for most cases, though we still need to update
apps to really forbid it for good.
I had also to update a few messages that …

Implement most of the states and transitions as chronos expects

---

CHANGELOG.md
package.json
src/modules/auth/switch.ts

As the title says, enable users to switch directly to a workspace in another account without having to type the `-w` option.

Implement `vtex switch {account}/{workspace}`

---

CHANGELOG.md
package.json
src/modules/init/index.ts

Add [vtex-apps/render-guide](https://github.com/vtex-apps/render-guide) and [vtex-apps/masterdata-graphql-guide](https://github.com/vtex-apps/masterdata-graphql-guide) to `vtex init`.

Add more apps to init

---

CHANGELOG.md
package.json
src/modules/infra/utils.ts

Fixes app version diff.
Shows this:
Instead of:

Fix versions diff

---

CHANGELOG.md
package.json
src/builder.ts
src/cli.ts
src/env.ts
src/modules/apps/link.ts
src/modules/auth/login.ts
src/modules/browse/admin.ts
src/sse.ts

This PR intends to enable VTEX Toolbelt to target any VTEX IO cluster
by providing the routing cookie on some routes, and adding the
cluster id domain infix in other routes.
To allow VTEX Toolbelt to communicate with any VTEX IO clutser
This generalizes the communication between toolbelt and vtex io clusters, in such a way that we're no longe limited to two environments (prod and staging), but we can out-of-the-box to use it against any created environment
Basically execute common operations against multiple clusters, by specify the environment variable `VTEXIO_REGION`

Add VTEX IO cluster targeting

---

CHANGELOG.md
package.json
yarn.lock

Add dependency `js-yaml` that was being used in `vtex release` but not declared in `package.json`.

Add missing dependency

---

CHANGELOG.md
package.json
src/modules/apps/link.ts

Fix `relink` behavior for linked node dependencies.
The previous implementation assumed that `cwd === appRoot`, which is not true anymore.
As result of this when one executed `vtex` in any folder nested in the app root folder, the path of linked dependencies was calculated relatively to the nested folder, breaking the server side.
`cd {node-vtex-api-folder}`
`yarn link`
`cd {any-vtex-app-which-depends-on-it}/node`
`yarn link @vtex/api`
`vtex link`
`# Update (or just save) some file in node-vtex-api`
This should send the correct path of the dependency to `builder-hub`.

Use relink path for linked deps based on app root

---

CHANGELOG.md
package.json
src/modules/apps/update.ts
src/modules/infra/utils.ts

This PR partially reverts the changes made in #504. In order to get the latest app version with a fixed major, the `vtex update` command was trying to access a route in VTEX Registry that is forbidden for non-VTEX users.

Stop trying to get forbidden app manifests

---

CHANGELOG.md
package.json
src/greeting.ts
src/modules/auth/whoami.ts
src/modules/index.ts

Add information about workspace state (dev/production) to the `whoami` command, which is the go-to command for when you want to know where you are.
Since `whoami` is currently network-independent, I felt like it would be a regression to see it blowing up if the request for workspace state fails. To address this, I tried to make the failure not stop the rest of the command, opting for just displaying an error message and omitting the information we could not fetch. See example screenshot if this is not clear enough.
People are used to running `vtex whoami` to get info about the current account and workspace, so they end up having to run two commands to get the necessary info.
Run `vtex whoami` and see the prepended workspace status.

Add workspace state (dev/production) to whoami message

---

CHANGELOG.md
src/modules/workspace/create.ts

This PR solves the `403 Forbidden` error that is raised when toolbelt is querying Colossus for the route map after creating a new workspace.
The solution was to:
- Request vtex.builder-hub's availability for route map warm-up instead of querying Colossus, which is something not every user is allowed to do.

Check builder-hub's availability for route map warm-up

---

CHANGELOG.md
package.json
src/cli.ts
src/host.ts
src/modules/apps/link.ts

As the title says, to avoid `vtex link` failures.

Add retries for builder-hub availability requests and debugger connections

---

CHANGELOG.md
package.json
src/clients.ts
src/modules/apps/link.ts
src/modules/infra/update.ts
src/modules/tree.ts
yarn.lock

This PR:
- Upgrades to @vtex/api@^3.0.7.
- implements the `--unsafe` (or `-u` option) for the `vtex link` command, which enables apps being linked with typescript errors.

Upgrade to @vtex/api@^3.0.7 and Implement --unsafe link option

---

CHANGELOG.md
README.md
package.json
src/modules/release/index.ts
src/modules/release/utils.ts
src/modules/tree.ts

This PR makes the `vtex release` command accept a valid (semver) version as its first argument.
It can be used if the user wants to specify the exact new version instead of having it automatically bumped.

Accept valid (semver) versions as first argument for vtex release

---

CHANGELOG.md
package.json
src/modules/apps/link.ts

This PR makes the `vtex link` command check if the app uses the node builder before trying to start the debugger tunnel. Therefore the message `Failed to start debugger` will not appear if the user is linking apps that do not use the `node` builder.

Start debugger tunnel only for node apps

---

CHANGELOG.md
package.json
src/locator.ts
src/modules/apps/publish.ts
src/modules/build.ts
src/sse.ts

This PR makes toolbelt display only logs sent by `builder-hub` or `apps` during a `publish`.
During a build, toolbelt displays to the user all logs that either has the corresponding app as `subject` of the message or has no subject at all. Since `publish` runs on workspace `master`, this causes toolbelt to show a lot of unrelevant logs to the user.

Fix unrelevant logs being shown during publish

---

.npmignore
CHANGELOG.md
package.json

As the title says, to prevent files in `.git` to be published by `npm`.

Add .git to .npmignore and fix changelog

---

CHANGELOG.md
package.json
src/modules/workspace/abtest/finish.ts

This PR makes the following change:
- When running `vtex workspace abtest finish`, the output message `All A/B testing is now finished.` was replaced by `A/B testing with workspace {currentWorkspace} is now finished`.

Fix A/B test finish message

---

CHANGELOG.md
package.json
src/modules/apps/link.ts

As the title says.
With the current value of `300ms`, making simultaneous changes to multiple files would sometimes cause toolbelt to send multiple `patch` requests to Builder-hub instead of a single request with all changes.
One relatively consistent way of reproducing this bug is by linking `@vtex/api`:
- In `node-vtex-api` root folder, run `yarn link`, then `yarn watch`.
- Pick any node app and run `yarn link @vtex/api` in the `node` folder.
- `vtex link` your app.
- Make any change to `index.ts` in `node-vtex-api`. This should trigger 3 file change events.
Before changes, toolbelt would sometimes make two requests to Builder-hub (this can be verified by either looking at the logs of the pod running Builder-hub or observing another build happening right after the first one had …

Increase watcher debouncer wait time to 1s

---

CHANGELOG.md
package.json
src/modules/workspace/abtest/finish.ts
src/modules/workspace/abtest/start.ts
src/modules/workspace/abtest/status.ts
src/modules/workspace/abtest/utils.ts
yarn.lock

As the title says. Throws a nice message if the `vtex.ab-tester` is not installed:

Check if vtex.ab-tester is installed before attempting to use it

---

CHANGELOG.md
package.json
src/conf.ts
src/host.ts
src/modules/apps/link.ts
src/modules/apps/publish.ts

Locally store a host used in a link or publish. If another link or publish is done within a certain threshold, try to reuse that host.
By reusing a host, we can take of advantage of caches from previous builds.
``vtex link``
``vtex publish``

Persist StickyHost between links and publishes

---

CHANGELOG.md
package.json
src/modules/workspace/create.ts

As the title says. Experience shows that workspaces with hyphens in their names can cause trouble when trying to access URLs exposed by linked apps.

Do not allow users to create workspace names with hyphens

---

CHANGELOG.md
package.json
src/greeting.ts

If toolbelt is unable to read the current workspace's state, it must be logged out of the platform. This PR makes the `vtex whoami` message replace the `Logged into` message part by `Not logged in. Previously logged into` in this case.

vtex whoami shows better message if unable to read workspace state

---

CHANGELOG.md
package.json
src/modules/apps/unlink.ts
src/modules/deps/update.ts

As the title says, this PR makes `vtex deps update` correctly print an eventual error message.

Fix error parsing in vtex deps update

---

CHANGELOG.md
package.json
src/modules/workspace/abtest/status.ts

Prints a special message if ab-tester returns null variables (`status` route) this is the case.

Check if ab-tester returns null variables in status

---

CHANGELOG.md
README.md
package.json
src/modules/apps/link.ts
src/modules/apps/publish.ts
src/modules/setup.ts
src/modules/tree.ts

This PR:
- Fixes asset-server URL for typings bundle fetching when an app dependency is published (use `{vendor}.vteximg.com.br/...`)
- Implements retries in the `typingsInfo` function to account for failure in the communication with vtex.builder-hub.
- Moves typings fetching to a separate command `vtex setup`
- Implements eslint configuration download in the `vtex setup` command
- Implements merging of tsconfig entries downloaded from builder-hub (vtex/builder-hub#523)
- Makes `vtex link` run `vtex setup` by default, at the beginning of the linking process. Using `vtex link --no-setup` will make it skip this step.
- Guarantees that everything works fine even when the user runs `vtex link` in some folder below the app's root.

Fix typings fetching and download tslint and tsconfig

---

CHANGELOG.md
package.json
src/host.ts

Temporarily disable saving `stickyHost` locally (#540)
Due to the current routing logic, patches are not being sent to the same pod if `stickyHost` dies. Will be enabled when this behavior is fixed.
-  [X] Bug fix (non-breaking change which fixes an issue)

Temporarily disable saving StickyHost locally

---

CHANGELOG.md
package.json
src/modules/apps/debugger.ts
yarn.lock

This PR contains two changes to the Node debugger logic:
- Don't close debugger server on an unexpected response;
- Ping the debugger `WebSocket` every 30s so the connection doesn't get closed due to inactivity.
Currently it is almost impossible to use the Node debugger, because it stops working shortly after the apps starts running. This is an attempt to make it more stable.
Link one or more Node apps and attach the debugger to them. Verify the debugger continues working even after a long period (1h+) of inactivity.

Improve Node debugger stability

---

CHANGELOG.md
package.json
src/modules/release/utils.ts

This PR makes `vtex release` work correctly even if the user's `cwd` is below the app's root.

Fix app root resolution for vtex release

---

CHANGELOG.md
package.json
src/modules/apps/link.ts
src/modules/apps/publish.ts
src/modules/setup.ts
src/modules/utils.ts

As the titles says, to avoid inconsistencies between `yarn.lock` and `package.json` when the code is processed by `builder-hub`.

Always run yarn locally on link and publish (react and node folders)

---

CHANGELOG.md
package.json
src/host.ts

Re-enable StickyHost that was disabled on #549 , since `kube-router` was fixed on vtex/kube-router#719
Link app, kill builder-hub and relink. Check if `sticky-host` is always present, even if locally saved.

Enable saving StickyHost locally

---

CHANGELOG.md
package.json
src/locator.test.ts
src/locator.ts
src/manifest.ts
src/modules/apps/link.ts
src/modules/apps/utils.ts
src/modules/init/index.ts
src/modules/setup.ts
src/typings/global.d.ts

After each `vtex link`, toolbelt will try to write `$schema` tag on `manifest.json`
After vtex/node-vtex-api#155, manifest has a [JSON schema](https://json-schema.org/).
Adding it to `manifest.json` will help the user to write (autocomplete) and validate (typed fields) their manifest.
1. `vtex link`
2. Check for `$schema` on `manifest.json`

Add JSON schema to Manifest

---

package.json
src/locator.ts
src/modules/apps/update.ts

Trying to update the major makes the API call to apps fail, as the
apps service currently doesn't allow an installation request to change
the major of an existing installation. I'm removing that check in
apps, but for that we need to make toolbelt not accidentally update
the apps majors in users' accounts.
That would erroneously make many people update their apps to
the latest majors, when many times the latest major are actually
"unstable" and kept in active development until they are actually
released (when we would normally update the accounts automatically).
This is currently the case for many apps such as vtex.admin, vtex.store,
render-server, render-ssr, etc.
- Run `vtex update`
- Check that no updates of majors are suggested
- Profit

Stop making `vtex update` attempt to update app major

---

CHANGELOG.md
README.md
package.json
src/modules/tree.ts
src/modules/url.ts

This PR implements the `vtex url` command which prints the base URL for the current account, workspace and evironment ('prod' or 'staging').

Implement `vtex url` command

---

CHANGELOG.md
package.json
src/modules/auth/login.ts

This PR adds the following condition when checking if `vtex.admin-login` is installed in the current account/workspace:
- checks if the data returned by the request to `vtex.admin-login` contains the appId "vtex.admin-login", which should indicate that it is actually the app's response, and not a generic "not found" page generated by the website.

Correctly check if `vtex.admin-login` is installed in current account/workspace

---

CHANGELOG.md
package.json
src/modules/utils.ts

This PR adds double quotes around the resolved `yarn` path so calling `yarn` also works in Windows platforms.

Wrap yarn path in double quotes to avoid errors with spaces in path name

---

CHANGELOG.md
package.json
src/modules/init/index.ts

The `builders` prop in the `manifest.json` file of the cloned app was always being set to `{}` with `vtex init`.
This PR fixes the issue.

Fix `vtex init`

---

CHANGELOG.md
package.json
src/modules/apps/update.ts

When issuing `vtex update`, the confirmation table (containing the previous and new versions of installed apps) had red headers.
This PR changes the color of the headers to yellow.

Change color of vtex update table headers to yellow

---

src/clients/abTester.ts
src/modules/workspace/abtest/finish.ts
src/modules/workspace/abtest/start.ts
src/modules/workspace/abtest/status.ts
src/modules/workspace/abtest/utils.ts

Initialize A/B test adapted to the new API, which doesn't need anymore to tell the confidence level.
Now `ab-tester` declares a new route to initialize a test which doesn't require a value o confidence level. This PR aims to initialize the test with this new format but also maintain support for old version of `ab-tester`.
Try to initialize a A/B test with IO CLI and verify if works well.

Initialize A/B test with new API

---

src/modules/workspace/abtest/start.ts
src/modules/workspace/abtest/status.ts

First, add the new A/B Test's info `pValue` to the response of A/B Test status and add a missing information, the values of conversion rates when we only looked to the data retrieved in the last 24 hours. Also, we should change a bit the way we show these informations trying to make it clearer and easy to understand.
We need to return a more descriptive information about an A/B Test.
Initialize an A/B Test and check if the status of the test changed as described.

Update A/B Test Status

---

CHANGELOG.md
package.json
src/conf.ts
src/modules/auth/switch.ts
src/modules/workspace/use.ts

Allow to use `vtex switch -` and `vtex use -` to switch account/workspace back to previous one used. Just like `git checkout -` or `cd -`. 
Not exactly a problem, but it would be a nice to have.
```shell
vtex switch account1
vtex switch account2
vtex switch - # should switch to `account1`
vtex switch - # should switch to `account2`
vtex switch - # should switch to `account1`
```
```shell
vtex use workspace1
vtex use workspace2
vtex use - # should switch to `workspace1`
vtex use - # should switch to `workspace2`
vtex use - # should switch to `workspace1`
```

Allow to pass "-" to switch to last used workspace/account

---

CHANGELOG.md
package.json
src/host.ts

This stops toolbelt from saving the sticky-host locally.
The issue with the `fork-ts-checker-webpack-plugin` is making Builder-hub stall builds after the `Build accepted` message. This is worsened by the fact that toolbelt forces build requests to go to the same pod, so if the user ends up with a faulty pod, he won't be able to link until his sticky-host expires or the pod dies.
Use this toolbelt to link repeatedly and verify toolbelt gets a new sticky-host every time.

Stop saving sticky-host locally

---

CHANGELOG.md
package.json
src/modules/utils.ts

Since the local code will be built with `vtex.builder-hub`, it makes no sense to have `yarn` checking if the dependencies in a project's `package.json` are compatible with the local version of `node`.

Use `ignore-engines` flag when running `yarn`.

---

CHANGELOG.md
package.json
src/cli.ts
src/modules/housekeeper/update.ts
src/utils.ts

This PR fixes the `vtex update` command by making it show available `runtimes` updates.
Moreover, the `vtex update` command will now list available `infra` and `runtimes` updates only when run with the `--verbose` option. Otherwise it will only show that there are availble `infra` and/or `runtimes` updates without listing them.

Make vtex update show runtimes updates

---

CHANGELOG.md
package.json
src/modules/init/index.ts

This PR makes the `vtex init` command not show some unnecessary (back end examples) templates for users that are not from VTEX.

Do not show unnecessary templates for users outside VTEX

---

CHANGELOG.md
package.json
src/modules/init/index.ts

Do not show `masterdata-graphql-guide` in `vtex init` for users outside VTEX.

Add masterdata-graphql-guide to vtex internal templates

---

CHANGELOG.md
package.json
src/modules/apps/debugger.ts

In order to keep the debug of Node apps working we need to make sure that debug requests are handled by the runtime.
We want to remove the runtime from the default flow of requests, but it's needed in some situations, like debugging Node apps.
1. Configure the Toolbelt to use a cluster with a Router that can handle the new header (v3.1.14-beta.4, for instance)
2. Link the [Builder Hub](https://github.com/vtex/builder-hub/pull/662) that uses the runtime to start the app 
3. Link a Node app and go to `chrome://inspect` to make sure the debug tunnel is not open
4. Run this version of the Toolbelt so you can send the new `Runtime-Api` header
5. Link a Node app and go to `chrome://inspect` to make sure the debug tunnel is open

Add header to send debug requests to the runtime

---

CHANGELOG.md
package.json
src/sse.ts

Filter out artificial JSON objects that are meant to be logged to splunk, except in verbose mode
https://vtex.slack.com/archives/CK9QZV5JN/p1565206489045000

Filter out __VTEX_IO_LOGS except on verbose mode

---

CHANGELOG.md
package.json
src/modules/workspace/create.ts

After creating a new workspace, toolbelt always calls the the availability endpoint of build-hub to work the route map generation and cache it on router. The problem is: the endpoint which has been used to warm it up is private, and route map are only built to public endpoints.
Remove unnecessary code. Once this code never warmed up the route map build and we there aren't "tickets" about timeout on the first request, we don't need sending a request to builder-hub anymore.
- Create a new workspace
- Open the account admin on it (you should not receive a timeout)

Remove request to builder-hub when a new workspace is created

---

CHANGELOG.md
src/clients/billingClient.ts
src/modules/apps/install.ts
src/modules/tree.ts

Add a parameter force in the cli for the app installation feature that will skip the check for route conflict. Therefore it will be possible to install an app even if it has route conflicts with app already installed in the workspace.
Trying to install an app that has route conflict with another app already installed in the workspace. Without the parameter force it should return an error and the app should not be installed. With the parameter force the app should be installed normally.

Add a parameter to skip route conflict check in app installation

---

CHANGELOG.md
package.json
yarn.lock

Update chokidar to new [version](https://github.com/paulmillr/chokidar).
> v3 (Apr 30, 2019): massive CPU & RAM consumption improvements; reduces deps / package size by a factor of 17x and bumps Node.js requirement to v8 and higher.
Possibly remove some dependencies vulnerabilities and improve performance
`Chokidar` package is responsible for watching file changes on link. To test just `vtex link` an app an make sure changes are being read.
To install this version:
`git clone --branch fix/update-chokidar https://github.com/tiagonapoli/toolbelt.git && cd toolbelt && yarn && yarn global remove vtex && yarn global add file:$PWD`

Update chokidar package

---

CHANGELOG.md
package.json
src/modules/apps/publish.ts
src/modules/tree.ts
yarn.lock

A new feature to check that SemVer is being obeyed when publishing an app has been developed for the node builder in builder hub. This PR creates a parameter to skip this check and publish the app even if it violates SemVer.

Add parameter force to skip SemVer ensure in app publish

---

CHANGELOG.md
package.json
src/cli.ts
src/conf.ts
src/logger.ts
yarn.lock

This PR makes some changes to toolbelt's logging facilities:
- Loggers are now built using the `createLogger` function from `winston`, which receives _transports_ that log differently depending on the log scope.
- Every log (starting on debug level) will now be stored locally in a `vtex_debug.json` file.
- The `simpleConsoleTransport` is used for every other command, as well as for `vtex link --verbose`. It replicates the functionality of toolbelt's previous default logger.

Improve logger

---

CHANGELOG.md
package.json
src/modules/rewriter/delete.ts
src/modules/rewriter/export.ts
src/modules/rewriter/import.ts
src/modules/rewriter/utils.ts
src/modules/tree.ts

This PR implements the `--reset` option in the `vtex redirects import` command, along with fixes to both file existence and CSV format validations.

Implement --reset option in vtex redirects import

---

CHANGELOG.md
package.json
src/cli.ts
src/modules/rewriter/delete.ts
src/modules/rewriter/export.ts
src/modules/rewriter/import.ts

Since this project upgraded the version of the `winston` dependency, the logging of error objects have stopped working. This PR makes the project use `console.log` to show error objects when the `--verbose` flag is set.

Temporarily use console.log to print errors

---

CHANGELOG.md
package.json
src/logger.ts

Fix error logging
- Install this branch
```bash
git clone git@github.com:vtex/toolbelt.git && \
cd toolbelt && git checkout fix/error-logging && \
```
- Go to your global yarn `node_modules/vtex/lib`: 
```bash
cd ~/.config/yarn/global/node_modules/vtex/lib
```
- Run any log modifying the snippet: 
```bash
node -e "require('./logger').default.error(new Error('sample error'))"
```
Check the output and `vtex_debug.txt` as well: 
```
code ~/.config/configstore/
```
The logs:
```js
logger.info('Hello')
logger.info('msg1', 'msg2', new Error('Error 1'))
logger.info(new Error('Error 2'))
logger.error(new Error('Error 3'))
logger.debug('Test %s usage: %s %s %s', '123', '234')
logger.debug('a', 'b', 'c', { a: 54 }, 'd', 'e')
logger.debug({ a: 100, b: '123' }) …
```

Fix error logging

---

CHANGELOG.md
package.json
src/__tests__/modules/setup/setupESLint.test.ts
src/modules/setup/setupESLint.ts

`eslint`, `eslint-config-vtex` and `eslint-config-vtex-react` have new versions 
```
git clone git@github.com:vtex/toolbelt.git && \
cd toolbelt && git checkout feature/update-vtex-setup-packages && \
```
Go to any app, remove eslint, eslint-config-vtex and eslint-config-vtex-react from one or more of its builders package.json. Run `vtex setup`.
Check all package.json, they should have the updated version of the packages mentioned above

 Update versions of eslint related packages added by vtex setup

---

CHANGELOG.md
package.json
src/cli.ts
src/typings/package.json.d.ts

Now that node >= v10 is required some user errors reports are reaching us because the error is not clear at all. We though just adding `"engines": { "node": ">= 10" }` was sufficient, and in some cases are, but for some reason npm doesn't ensure node version for every install. Because of this a check was added and if node version is older than the defined on `package.json` `engines.node` a error log is showed.
Additionally, logs on the command run and OS basic information was added.
Install this toolbelt branch:
```
git clone git@github.com:vtex/toolbelt.git && cd toolbelt && \
git checkout feature/check-node-version && \
```
Run any `vtex` command with `node` < v10. A log `Incompatible with node < v10. Please upgrade node to major 10 or higher.` should …

Ensure node version and log command and OS detail

---

CHANGELOG.md
package.json
src/clients/rewriter.ts
src/modules/rewriter/utils.ts

This PR improves the overall experience of the `vtex redirects import` command by sorting the list of `from` URLs before starting to import and by increasing timeout and number of retries of the `rewriter` client.

Improve redirect importing performance

---

CHANGELOG.md
package.json
src/modules/init/index.ts

- Fix `vtex init` for `react-app-template`
- Remove `err.printStackTrace()`, which could be undefined
Clone and install globally this branch:
```
git clone git@github.com:vtex/toolbelt.git && \
git checkout fix/init-react && \
```
Run `vtex init` and select `react-guide`.

Fix vtex init for react-app-template

---

CHANGELOG.md
package.json
src/modules/prompts.ts

Fix issue where CTRL+C couldn't terminate the process after prompting log in.
This happens because `process.stdin` is set to `rawMode` and is not reset. According to [node docs](https://nodejs.org/api/tty.html#tty_tty):
> When Node.js detects that it is being run with a text terminal ("TTY") attached, process.stdin will, by default, be initialized as an instance of tty.ReadStream and both process.stdout and process.stderr will, by default be instances of tty.WriteStream. The preferred method of determining whether Node.js is being run within a TTY context is to check that the value of the process.stdout.isTTY property is true
And:
> When in raw mode, input is always available character-by-character, not including modifiers. Additionally, all special processing of characters by the …

Fix CTRL+C not terminating the process

---

CHANGELOG.md
package.json
src/__tests__/fixtures/manifests/index.ts
src/__tests__/modules/setup/mocks.ts
src/__tests__/modules/setup/setupESLint.test.ts
src/modules/setup/index.ts
src/modules/setup/setupESLint.ts
src/modules/setup/utils.ts

Updates the `vtex setup` command to match the current [recipe](https://docs.google.com/document/d/1ePi5Mn3pe1dOorKrMtC-MclBDiIDimVzf0Uj61W8lA4/edit) instructions. This creates a `package.json` at the root of the app (alongside the `manifest.json`) with all ESLint dependencies.
Since ESLint newest major, they've changed how the package imports some dependencies (such as shared configs), making them break if you load your eslint plugin other than the folder that it is installed. For example, if you have you eslint and dependencies installed in a `node` folder, and you open the repo in the root, some ESLint plugins may not work properly, because they are installed in a child directory, not the one that the editor plugin is running.
Build the toolbelt and run `vtex setup` in any IO app. It …

Update ESLint setup to match current recipe instructions

---

CHANGELOG.md
package.json
src/modules/rewriter/import.ts

This PR fixes the command `vtex redirects import` when it is called with the `reset` option and the redirects index in `vtex.rewriter` is empty.

Fix redirects import when called with the `reset` option

---

CHANGELOG.md
package.json
src/__tests__/modules/setup/setupESLint.test.ts
src/modules/setup/setupESLint.ts

Modifies the merge of `package.json` in the ESLint setup to not override custom set options.
The `package.json` existing in the root of the app was always being overwritten with the base options, but it should be preserved.
Build the toolbelt and run `vtex setup` in any IO app, with a custom root `package.json`. The options in the existing file should be preserved.

Fix base package.json overriding custom one in setup

---

CHANGELOG.md
package.json
src/modules/apps/file.ts

We need sending the CHANGELOG.md when the app is published in order to show it in the notifications channel (and in our admin of releases in the future). 
- Publish em app with CHANGELOG
- Check the files published with the app: `GET http://apps.aws-us-east-1.vtex.io/<vendor>/master/registry/<app_name>/x/files`

Remove changelog from ignored published files

---

CHANGELOG.md
package.json
src/clients/sponsor.ts

This PR makes toolbelt use the specialized `tenant-provisioner` app to set account's editions.

Use `tenant-provisioner`'s `migrate` API to set account's editions

---

CHANGELOG.md
package.json
src/modules/local/account.ts
src/modules/local/token.ts
src/modules/local/utils.ts
src/modules/local/workspace.ts
yarn.lock

Skip the "copy to clipboard" function on systems that don't support it.
When running the `clipboardy.writeSync` function on systems that don't have a display attached (e.g. WSL, or when running on TTY) or a X.Org server running, the function throws an error because it uses `xsel` under the hood.
Run the `vtex local token` command on a TTY. No error should be thrown and the token should be displayed as normal.

Fix error when running on TTY

---

CHANGELOG.md
package.json
src/modules/local/utils.ts

Make `vtex local token` great again when used on Mac OS.
Try to run `vtex local token` in different OS.

Fix copy to clipboard on mac os

---

CHANGELOG.md
package.json
src/modules/setup/setupESLint.ts
src/modules/workspace/create.ts

When a new workspace is created using toolbelt, the CLI also warm up the route map performing a request to check the availability of builder-hub. This was implemented to decrease the chances of the user receives a timeout in the first requests which demands a route map generation in the workspace. But sometimes this timeout is received with the request to builder-hub, and actually we don't need to treat this error because the route map was warmed up anyway.
Do not show errors when toolbelt tries warming up the route map of a new workspace, once the user doesn't know that it's happening and he/she can't do nothing in case of errors. 
- Uninstall builder-hub from some account
- Create a new workspace on this workspace
- The request to builder-hub will failed, but no error must be showed by …

Ignore errors warming up the route map after create a workspace

---

CHANGELOG.md
package.json
src/Token.ts
src/cli.ts
src/conf.ts
src/modules/auth/login.ts
src/modules/auth/switch.ts

`vtex switch` needs to open the browser on every execution. Now used tokens are stored to later usage by `vtex switch`
```
git checkout feat/switch-without-opening-broser && \
```
Use `vtex --verbose switch`

Switch accounts without opening browser when possible

---

CHANGELOG.md
package.json
yarn.lock

Update version of node-vtex-api to use https.
- Do not traffic user token explicit over the network.
- https://vtex.slack.com/archives/C2WSEU9QQ/p1574359544270200
Try to link vtex.styleguide.

Update node-vtex-api to use https

---

CHANGELOG.md
package.json
src/clients/abTester.ts
src/clients/rewriter.ts

Use `vendor.appname@major.x` on `AppClients` constructors.
This will solve the message:
```
is using old routing for vtex.rewriter. Please change vendor.app to vendor.app@major in client
```
```
git checkout fix/old-routes && \
```
Try to link and check if the message is gone

Fix clients constructors

---

CHANGELOG.md
package.json
src/sse.ts

Use the colossus feature which allows us sends an event when the link connection is closed.
https://github.com/vtex/colossus/pull/287
Now we can notify the users when the "link experience" is not turned on anymore sending an event, which can be catch by an app and shows some kind of notification on browser.
- Install colossus@0.36.0-beta
- Use this toolbelt to link some app
- Close the terminal or just turn off the link
- Check on splunk: `index=colossus account=<account> workspace=<workspace> key=link_interrupted`
You can also link an app which is expected to receives a `link_interrupted` event from colossus.

Notify IO when link connection is closed

---

CHANGELOG.md
package.json
src/modules/sponsor/setEdition.ts
yarn.lock

Fix `edition set` command to allow setting the initial edition of an account.
That request must be performed from `vtex` root spnsor, so the change is
to stop giving an error when the account has no sponsor and calling from the
`vtex` account instead.
Not allowing to set initial edition of an account from toolbelt.
- Find an account without any edition (e.g. any `vtexgameX` where `X` not in `[42-45]`)
- Ensure that with `vtex edition` which should return a 404
- Try setting edition `vtex edition set <edition>` (e.g. `vtex.edition@0.x`)
- Should change to `vtex` account and set edition successfully

Allow setting initial edition of accounts :evil-parrot:

---

CHANGELOG.md
package.json
src/modules/init/index.ts

This PR makes the `vtex init` command never modify the cloned app's manifest.

Do not change app manifest when cloning with `vtex init`

---

CHANGELOG.md
package.json
src/cli.ts
src/conf.ts
src/nps.ts

This feature will make toolbelt ask for user feedback whenever he issues any command. 
If the user accepts giving feedback, his browser will automatically open this [Google Form](https://forms.gle/CRRHn6P3x9AeaWTQ8). It will then ask for feedback again in 3 months.
If the user does not want to give feedback, he will be prompted about being reminded again in the future.

Implement feedback asking functionality

---

CHANGELOG.md
package.json
src/modules/rewriter/export.ts

The ranges of redirect batches to be exported were being wrongly generated, which caused duplicated entries in the exported file. This PR fixes it.

Fix redirects export

---

CHANGELOG.md
package.json
src/cli.ts
yarn.lock

Using [v8-compile-cache](https://www.npmjs.com/package/v8-compile-cache) may improve toolbelt commands startup times.

Use v8-compile-cache

---

CHANGELOG.md
package.json
src/modules/apps/deprecate.ts
src/modules/apps/publish.ts
src/modules/apps/undeprecate.ts

- Refactor `vtex deprecate` and `vtex undeprecate`
- Use `ManifestEditor` on `vtex publish`
```
git checkout refactor/deprecate-undeprecate-publish && \
```
Test these scenarios:
```
For `vtex deprecate` - `vtex undeprecate`:
// In the project
git clone https://github.com/vtex-apps/service-example.git && cd service-example
vtex-test deprecate
vtex-test undeprecate
// Deprecate by name
vtex-test deprecate vtex.service-example@0.0.5
vtex-test undeprecate vtex.service-example@0.0.5
-------------------------------------------------------------------------------------------
For `vtex publish`:
git clone https://github.com/tiagonapoli/service-example.git && cd …
```

Refactor `vtex deprecate` and `vtex undeprecate`

---

CHANGELOG.md
package.json
src/modules/apps/publish.ts

Changes on publish will start to take efect on January, 2. This has to be communicated to the user.
To test:
```
git checkout chore/publish-changes-message && \
```
Try to publish an app

Add message regarding publish changes when trying to publish

---

CHANGELOG.md
src/modules/apps/link.ts
src/modules/apps/publish.ts

```
git checkout  chore/improve-update-message && \
```
Try to link - builder-hub will throw an error because of the version.
Try to publish and check for the new prompt

Add publish confirm prompt and how to update toolbelt on builder-hub's update request

---

CHANGELOG.md
src/update.ts

Include the changelog URL and other improvements to the update-notifier.
Fixes #677 ("Make update notification better")
Change `const notifier = updateNotifier({ pkg, updateCheckInterval: 1000 * 60 * 60 * 1 })` to `const notifier = updateNotifier({ pkg, updateCheckInterval: 1 })` and run `npm run build && node ./lib/cli.js`
**Old:**
**New:**
Not the best way to do it since we're adding a lot of technical debt. It'd be better to create an issue to change the module when possible.

updateNotifier: add changelog url & improvements

---

CHANGELOG.md
package.json
src/modules/apps/publish.ts

If the terminal truncated the previous URL and the user clicked to open it, the URL copied to the browser could be incomplete. Using a shortener may solve the problem
```
git checkout fix/publish-url && \
```
Try to publish any app. The new publish process prompt will show up - then test the link.

Fix publish docs URL and warn about 'vtex validate' on publish

---

CHANGELOG.md
src/sse.ts

- Log url for auth-sse
```
git checkout chore/log-event-server-url && \
```
Try to `vtex login --verbose` - it will debug the auth-sse URL

Log url for auth-sse

---

CHANGELOG.md
package.json
src/cli.ts

- Log request url on unhandled errors when request.status is available and is 4xx or 5xx
- Debug response headers on unhandled errors when available - when the user doesn't run the command with `--verbose` it will be available on `vtex_debug.json`.

Improve unhandled request errors logging

---

CHANGELOG.md
src/modules/release/utils.ts

Fix a bug that occurs primarily on Windows when running `vtex release` if the some path has special chars like spaces eg: `C:\Users\Julio Moreira\foo\bar`.
Run `vtex release` on some directory that has spaces on it.

Fix: Escape `git add` filepath

---

CHANGELOG.md
src/modules/apps/utils.ts

Displays account name when confirming actions on master workspace.
Before:
After:

Add account name on master confirmation

---

src/modules/apps/deploy.ts
src/modules/apps/validate.ts
src/modules/tree.ts

`vtex deploy` has much better semantics than `vtex validate`.
```
git checkout chore/change-validate-to-deploy && \
```
Run `vtex validate` to check the deprecation message.
To reset to the official toolbelt version just run `yarn global add vtex`

Deprecate vtex validate and use vtex deploy instead

---

CHANGELOG.md
src/lib/manifest/ManifestEditor.ts
src/modules/apps/debugger.ts
src/modules/apps/link.ts
src/modules/apps/unlink.ts
src/modules/apps/utils.ts

Install this toolbelt branch:
```
git checkout refactor/unlink && \
```
```
// Same project link and unlink
git clone https://github.com/vtex-apps/checkout-summary.git && cd checkout-summary
vtex link --verbose
vtex list
vtex unlink --verbose
vtex list
// Many project unlinks
vtex unlink --verbose vtex.checkout-summary@0.x vtex.builder-hub@0.x
```
Apparently many project unlinks aren't working, even on the current stable version. I'm suspecting it's an Apps issue.

Refactor `vtex unlink`. Use ManifestEditor class on `vtex link`

---

CHANGELOG.md
src/modules/apps/publish.ts

```
git checkout fix/post-publish-message && \
```
Test publishing an app and check the post publish message

Fix post publish message notifying about deprecated 'vtex validate' command

---

CHANGELOG.md
src/modules/apps/link.ts

When builder-hub asks for a new toolbelt version and the toolbelt is on an older version it will respond with an error. Now toolbelt just retries many times until the retry limit, which is annoying. This PR fixes this.

Short circuit bad toolbelt version error

---

.gitignore
CHANGELOG.md
jest.config.js
package.json
src/lib/packageJson/index.test.ts
src/lib/packageJson/index.ts
src/lib/pinnedDependencies.ts
src/modules/apps/link.ts
src/modules/apps/testCommand.ts
src/modules/tree.ts
src/modules/utils.ts
yarn.lock

Scope pinned dependencies by builder.
This change requires https://github.com/vtex/builder-hub/pull/823
With new runtime 6 we would like to force `@vtex/api` on version `^6.0.0`.
Link this builder-hub branch:
```
git clone git@github.com:vtex/builder-hub.git && \
cd builder-hub && \
git checkout feat/scoped-pinned-dependencies && \
vtex link --verbose
```
Use this toolbelt branch:
```
git checkout  feat/scoped-pinned-deps && \
```
- Go to a project and change node/react typescript version. After `vtex link` or `vtex test` the version should be pinned to `3.7.3`.
- Go to a project with node@4.x. Change the `@vtex/api` version on the node's `package.json` and `vtex link` or `vtex test`. …

Scope pinned dependencies by builder

---

CHANGELOG.md
src/logger.ts
src/modules/build.ts

Logs from `ctx.vtex.logger.debug` on linked apps wasn't being logged on toolbelt on verbose mode 
```
git checkout feat/print-debug-events && \
```
Link and app in verbose mode and then link an app without verbose mode.
To reset to the official toolbelt version just run `yarn global add vtex`

Log debug events from linked apps

---

CHANGELOG.md
src/lib/files/ProjectFilesManager.ts
src/lib/files/YarnFilesManager.ts
src/lib/files/YarnLinkedFilesConfig.ts
src/modules/apps/file.ts
src/modules/apps/link.ts
src/modules/apps/publish.ts
src/modules/apps/testCommand.ts
src/modules/apps/utils.ts
src/typings/global.d.ts

Install this toolbelt branch:
```
git checkout refactor/yarn-linked-modules-management && \
```
Clone the two packages that will be used to test `yarn link`:
```
git clone git@github.com:tiagonapoli/test-pkg-a.git
git clone git@github.com:tiagonapoli/test-pkg-b.git
```
Clone the app that will be used to test:
```
git clone git@github.com:tiagonapoli/service-example.git && \
cd service-example && \
git checkout test/linked-npm-modules
```
Test `vtex link --verbose` and `vtex test --verbose` with this scenarios (maybe more that you think of):
- No modules yarn-linked
- One module yarn-linked - change the yarn-linked module files to check if the `vtex link` watcher works
- Two modules …

Refactor yarn linked modules sending

---

CHANGELOG.md
src/modules/apps/publish.ts
src/modules/tree.ts

Closes https://github.com/vtex/toolbelt/issues/713
`vtex publish` wasn't suitable for using in scripts
```
git checkout feat/publish-yes-flag && \
```
Try to `vtex publish` an app
To reset the toolbelt version run `yarn global vtex`

Create yes flag for 'vtex publish'

---

CHANGELOG.md
src/modules/infra/utils.ts

`vtex infra install sphinx@0.26.0-beta --verbose` is not working
```
git checkout fix/vtex-infra-install && \
```
Test `vtex infra install sphinx@0.26.0-beta --verbose`
To reset to official version just run `yarn global add vtex`

Fix vtex infra install creating semver object

---

CHANGELOG.md
src/__tests__/fixtures/manifests/index.ts
src/__tests__/modules/setup/setupTypings.test.ts
src/modules/setup/setupTypings.ts

`vteximg` host is being deprecated. It's necessary to use `vtexassets` instead.
```
git checkout fix/vtex-setup-urls && \
```
Run `vtex setup` in an app - check for the types urls on `node/package.json`, `react/package.json` if applicable

Use vtexassets host instead of vteximg

---

CHANGELOG.md
src/clients/rewriter.ts
src/env.ts

- Fix URL build when cluster is set
- Add cluster upstream header to billing client
```
git checkout fix/bugs-with-upstream-defined && \
```
Set a cluster to use:
```
vtex config set cluster 'test-3a'
````
Test using `vtex login`.
Check the host of the URL opened to be: `https://$account.$cluster.myvtexdev.com/`
Check `vtex link` if the pod is created on the specified cluster.

Fix bugs when cluster is defined

---

CHANGELOG.md
package.json
src/CLIPrechecker.ts
src/cli.ts
src/clients/npmClient.ts
yarn.lock

Installing toolbelt will just warn about the deprecation and will allow installation.
This PR will deactivate the installed version if it's deprecated
```
git checkout fix/check-npm-deprecation && \
```
Change the version on `package.json` to `2.86.0`:
```
code  $(yarn global dir)/node_modules/vtex/package.json
```
Try to run `vtex whoami` - it will warn about deprecation and close the process.

Add deprecation precheck

---

CHANGELOG.md
package.json
src/modules/apps/publish.ts

When publishing an app with the `-w` flag we use the builder-hub of the workspace used as parameter to the flag. However, if the operation is made in an account different from the app vendor the user will need to change the account during the publish process and the workspace used will be the one in the vendor account and not the one in the account the user was originally. Since this is not a behaviour we want, this PR blocks the use of `-w` flag in publishing if the account is different from the vendor.
Avoiding a weird behaviour.
Install this branch of toolbelt:
````
git checkout fix/publish-worksapce-flag-only-in-vendor-account && \
````
Try to publish an app like …

Error if not logged in vendor account during publish with `-w` flag.

---

CHANGELOG.md
src/__tests__/modules/setup/mocks.ts
src/__tests__/modules/setup/setupTypings.test.ts
src/modules/setup/setupTypings.ts
src/modules/setup/utils.ts

Updates the `setupTypings` step in `vtex setup` to sort the `package.json` dependencies prior to saving them, in order to match the behavior of `yarn` and `npm`.
When you ran `vtex setup` the dependencies were being saved in arbitrary order, so when you ran `yarn add foo` after the setup it changed the order of the dependencies added by the setup.
Run `vtex setup` in an app that should have dependencies, and `yarn test`.

Sort package.json entries when adding typings definitions

---

CHANGELOG.md
package.json
src/modules/init/index.ts

Implements the part in this [doc](https://docs.google.com/document/d/1zZ1gMIbGFHGIPaz0AuNekOpww3J-iyQJoTJrokhdmKc/edit) related to `vtex init`.
The others related PRs and new apps are: [builder-hub](https://github.com/vtex/builder-hub/pull/904), [checkout-ui-settings-server](https://github.com/vtex-apps/checkout-ui-settings-server) and [checkout-ui-settings](https://github.com/vtex-apps/checkout-ui-settings).
Making it easy to start an app to customize the checkout ui.
Just run `yarn watch` in this branch of toolbelt and then use `vtex-test` to run `vtex-test init`. The option `checkout-ui-settings` should be shown and, if selected, the template from [checkout-ui-settings](https://github.com/vtex-apps/checkout-ui-settings) should be downloaded.

Add checkout-ui-settings template in vtex init

---

.github/workflows/publish-prerelease-npm.yml
.github/workflows/publish-stable-npm.yml
package.json
scripts/publishLock.sh

Add a reminder step when publishing via `npm publish` without the CI.

Add npm publish lock

---

CHANGELOG.md
src/modules/init/index.ts

As title says
Repo: https://github.com/vtex-apps/connector-example

Add payment-provider-example to vtex init

---

src/modules/build.ts

I messed while trying to fix a lint error. 
I think there's no need to update changelog since the bug isn't released.
```
git checkout fix/event-listening && \
```
Try linking and/or publishing an app

Fix build event listening

---

CHANGELOG.md
src/modules/init/git.ts
src/modules/init/index.ts

Nowadays `vtex init` is too chaotic. Let's tidy up the house!
For now we will only allow the `store` template for users outside VTEX and also replace the `store-theme` (the current store template) for `store-framework-template`, that is simpler and easier for a quick start.

Remove all templates but `store` for non vtex users

---

CHANGELOG.md
package.json
src/modules/init/index.ts

@saviomuniz proposed a better template to be used as a boilerplate for `store`.
Improving the experience for a quick start in the platform.
Use `yarn watch` in this branch of `toolbelt` and then use the command `vtex-test init`. Select `store` and, if the repository `minimum-boilerplate-theme` is successfully cloned, everything is working :)

Change template for `store`

---

CHANGELOG.md
src/modules/init/index.ts

Add "edition app" option to `vtex init` pointing to https://github.com/vtex-apps/edition-hello
Cumbersome bootstrap of edition apps.
- `vtex init`
- `edition app`
- Check cloned folder

Add "edition app" vtex init option

---

CHANGELOG.md
src/clients/sponsor.ts
src/modules/sponsor/setEdition.ts

This is to allow setting the edition of an account in a separate workspace, something
that was not possible before and thus made testing editions quite cumbersome
(or dangerous).
With this, toolbelt starts calling the new API feature implemented by https://github.com/vtex/tenant-provisioner/pull/14
(this should be the last one to be merged)
Not being able to test an edition before actually setting it on the master workspace of an account.
- Run `vtex edition set` in a separate workspace
- Ensure workspace's edition has been set
- Ensure master's edition is untouched
- Also test it on `master` just in case

Allow testing editions in non-master workspaces

---

CHANGELOG.md
package.json
src/cli.ts
src/lib/error/ErrorCodes.ts
src/lib/telemetry/TelemetryCollector.ts
src/lib/telemetry/TelemetryReporter.ts
src/lib/telemetry/TelemetryStore.ts
src/modules/apps/list.ts

- Set an interval to remote flush in telemetry object to `toolbelt-telemetry` app.
- Pass telemetry object to `TelemetryReporter` in a file to avoid having errors since the object can be too large to be a cli argument.
- Send `TelemetryReporter` meta errors to `toolbelt-telemetry`.

Improvements in toolbelt telemetry

---

CHANGELOG.md
src/lib/error/ErrorKinds.ts
src/lib/error/ErrorReport.ts
src/lib/telemetry/TelemetryCollector.ts
src/lib/telemetry/TelemetryReporter.ts
yarn.lock

- Fix `stack` property on `ErrorReport` to save the `originalError` `stack`.
- Fix destructuring `err.response` - it may be `undefined`.
- Use `kind` instead of `code`, since `originalError` may already have a `code` property.
- Create `createGenericError` utility function.
- Fixes https://github.com/vtex/toolbelt/issues/773
Implementation errors on `ErrorReport` class.
```
git checkout fix/error-report-class && \
```
This is kinda difficult to manually test without inserting some `console.logs` inside the code or throwing manual errors :(
I tested adding a `throw Error('asdfasdf')` on `vtex ls` and adding a `console.log` on `TelemtryCollector` right after the …

Fix stack and code properties on ErrorReport

---

CHANGELOG.md
src/modules/setup/setupTooling.ts

Currently the `yarn format` script generated by `vtex setup` ignores `tsx` and `jsx` files. This PR fixes that.
n/a
n/a

Make yarn format also format jsx and tsx files

---

src/cli.ts
src/lib/metrics/MetricReport.ts
src/lib/telemetry/TelemetryStore.ts

As the title says, fixing some telemetry metrics bugs:
- Showing command path when it doesn't have an alias.
- Creating class instance from object for MetricReport.

Fix some bugs in telemetry metrics

---

CHANGELOG.md
src/lib/auth/AuthProviders/OAuthAuthenticator.ts
src/modules/browse.ts
src/nps.ts

This fixes the usage of `open`, allowing WSL users to successfully login again. 
On WSL:
```
yarn global add vtex@2.93.0-beta
```
Try to `vtex login`

Fix wsl url opening

---

CHANGELOG.md
src/modules/init/index.ts

Users that don't have a VTEX email should be able to use the template `checkout-ui-settings` to implement [checkout ui custom using apps](https://vtex.io/docs/components/functional/vtex.checkout-ui-settings@0.0.2).

Show checkout ui settings for users outside VTEX

---

CHANGELOG.md
src/lib/error/ErrorKinds.ts
src/lib/error/ErrorReport.ts
src/lib/telemetry/TelemetryCollector.ts
src/modules/setup/index.ts
src/modules/setup/setupTSConfig.ts
src/modules/setup/setupTooling.ts
src/modules/setup/setupTypings.ts
src/modules/tree.ts

- Allow granularity on what is being set up.
- Increase observability on errors being thrown when `vtex setup` is executed.
```
git checkout feat/create-new-setup-cmds && \
```
Test:
`vtex setup`
`vtex setup --tooling`
`vtex setup --tsconfig`
`vtex setup --typings`

Create new vtex setup flags

---

CHANGELOG.md
src/clients/Tester.ts
src/modules/apps/e2e/report/failedApps.tsx

Show logs after e2e test execution 
Facilitating the viewing of logs from e2e tests when running the vtex test e2e command via toolbelt
Get tester-e2e-cypress at branch `logs`
use yarn watch on the toolbelt
Pick an app with cypress tests that has a failing test (e.g shipping-preview)
add cypress builder at manifest: "cypress": "0.x"
link the app
link the tester-e2e-cypress
wait a couple seconds
run vtex-test test e2e at the app
after the test is completed check if there is a log file you can access

Add test logs url to vtex test e2e output

---

CHANGELOG.md
src/clients/runtime.ts
src/clients/sponsor.ts
src/lib/manifest/ManifestEditor.ts
src/locator.ts
src/modules/apps/debugger.ts
src/modules/debug/dotnet.ts
src/modules/support/login.ts
src/modules/utils.ts

We must not use HTTP from toolbelt. This PR converts the last of those into HTTPS by calling the new host. HTTP calls to `*.{{region}}.vtex.io` are deprecated and are soon going to stop working, which is also another reason to make this change now.
Another issue that is being fixed by this PR is the fact that we were not encrypting our websockets. Instead of `ws`, we should use `wss`. While this was a trickier change, as Kube Router had a bug that would not allow us to use the new URLs, this bug is fixed in `v6.2.3` and this can be updated here now.
There should be no other instances of `*.{{region}}.vtex.io` in this repo. I have looked for them and I believe I have updated the host everywhere. If any remains, please let me know and/or fix it.

Convert remaining HTTP calls to HTTPS

---

CHANGELOG.md
src/modules/rewriter/export.ts
src/modules/rewriter/import.ts
src/modules/rewriter/utils.ts

Some accounts have a `;` in their urls. This breaks the CSV, since we use `semicolon` as the separator (delimiter). To solve this issue, before exporting a `.csv` file, we need to encode the semicolon

Encode delimiter redirects

---

CHANGELOG.md
src/clients/billingClient.ts

This is an interesting bug. The log in install errors before were very unhelpful. That because billingClient, responsible to proxy the install request from toolbelt to Apps, use a graphql endpoint, and the way toolbelt handled these errors made obscure to the user what was the original error in the Apps API (what made it difficult to solve them). This PR should fix the issue making it easier for the users to fix install errors by themselves.
Screenshots with the error message logged: 
- before:
- with this PR:
Use this version of toolbelt:
```
git checkout feature/improve-error-logging-in-checkout && \
```
and try to install an app with peer dependencies like …

Improve logging in billingClient errors

---

CHANGELOG.md
src/modules/setup/index.ts

Fix a condition where `opts.all` were used instead of the local variable `all`.
The command `vtex setup` wasn't doing anything when no flags were passed.
Run `vtex-test setup` and it should correctly run all steps.
Before:
After:

Fix setup not running without any flags

---

CHANGELOG.md
src/commands/switch.ts
src/oclif/hooks/init.ts

Allow to customize help format. Add a blank line between command and description in help.
Improving help format.
With this branch, just use `--help` with any command and see if there is a blank line between the command and its description.

Customize help format

---

CHANGELOG.md
src/modules/apps/install.ts
src/modules/apps/uninstall.ts
src/modules/apps/utils.ts

When we killed `UserCancelledError`, we accidentally inserted a bug in the install command. When the user answered `no` to a prompt in the install command, the command continued.
This PR fix this bug.
Try to install an app in the master workspace of an account. A prompt will be showed asking if you are sure. Answer no to the prompt and check if the app was indeed **not installed**.

Fix install when user cancel command

---

CHANGELOG.md
src/modules/setup/setupTooling.ts

Updates the configuration of `lint-staged` to include GraphQL files when running prettier, alongside JSON.
Make all GraphQL files _prettier_ ✨

Add GraphQL files to lint-staged config

---

CHANGELOG.md
src/clients/evolutionManager.ts
src/clients/index.ts
src/modules/workspace/promote.ts

Now evolution manager have an api to save info about workspace promotions (to allow some audit). This PR makes toolbelt call this api when a `promote` command is used successfully.
Lack of audibility in workspace promotions.
This is a bit complicated since you will need to promote a workspace. My suggestion is to create a production workspace in a test account like `basedevmkp` and immediately promote it. Wait some seconds, then go to GraphiQL in that account admin, select `evolution-manager-graphql` as your app and try the query:
```
query getPromotions {
promotions { account, agent, workspace, createdIn }
}
``` 
The result should show your workspace promotion.

Save workspace promotion info

---

CHANGELOG.md
CODEOWNERS
src/clients/sponsor.ts
src/modules/sponsor/setEdition.ts
src/modules/workspace/common/edition.ts
src/modules/workspace/create.ts
src/modules/workspace/reset.ts
src/modules/workspace/use.ts

This is to reduce the noise about our current editions, by creating some
logic in toolbelt to automatically switch to the `edition-store` when the
current account is in the default edition `edition-business`.
The whole context is: 
- Stores have to be created with the initial edition `edition-business`, as we don't have any
information on whether it is going to be implemented in IO or Portal, and we don't want to
affect the provision experience of accounts running in the legacy/current platform. 
- If it is going to be developed in IO though, some user in the account will necessarily need to
create a workspace on it for development/test purposes.
- With that, we got to the realisation that the moment the user creates a workspace is the
ideal time to prompt them to switch their account's …

Auto-switch to edition-store when creating new workspace

---

src/clients/evolutionManager.ts
src/lib/error/ErrorKinds.ts
src/modules/workspace/promote.ts

- Handle evolution-manager not installed error
- Checkout to this branch
- `yarn watch`
- Run `vtex-test promote` on a created production workspace
Running `vtex-test promote` on basedevmkp, which doesn't have evolution-manager installed will help testing for this case
(no need to update changelog, this is a fix to an unreleased change)

Fix workspace promote reporting

---

CHANGELOG.md
src/lib/error/ErrorKinds.ts
src/modules/workspace/common/edition.ts

We were throwing a 404 exception on the code for
checking if the account edition was business.
We want to simply ignore any errors there, as this
is a non-crucial operation that should have no effect
if any error occurs. Especially if it is a 404, which means
that the account has no edition set.
We only need to do anything when the account is in the
`vtex.edition-business`, so a 404 should be 100% ok here.
Other errors will still be logged as non-fatal warnings, but
we will eat the exception.
Misleading error when creating or resetting workspaces.
- Go to account that has no edition
- Create or reset a workspace
- Should not get any error
- If some error occurs, should get a non-threatening warn log
Before and after:
Simulating a non-404 error (I actually inverted the condition in the …

Fix error on edition-less accounts

---

CHANGELOG.md
src/commands/workspace/delete.ts
src/modules/apps/link.ts

- Fix `force` flag type in `vtex workspace delete`
- Fix `no-watch` behaviour in `vtex link`
Some problems with flags after migrating to oclif.

Fix some flags issues

---

.eslintrc
CHANGELOG.md
package.json
src/CLIPreTasks/CLIPreTasks.ts
src/CLIPreTasks/OutdatedChecker/OutdatedChecker.test.ts
src/CLIPreTasks/OutdatedChecker/OutdatedChecker.ts
src/CLIPreTasks/OutdatedChecker/OutdatedCheckerStore.ts
src/CLIPreTasks/OutdatedChecker/checkForOutdated.ts
src/clients/toolbeltConfigClient.ts
src/lib/clients/index.ts
src/lib/constants/EnvVariables.ts
src/lib/error/ErrorKinds.ts
yarn.lock

- Create `OutdatedChecker` which will ask `toolbelt-config-server` about the latest version.
```
git checkout feat/use-toolbelt-config-server && \
```
- Run `vtex-test`. Check the file created on `~/.vtex/pretasks/outdated-checking.json`
- Change the version on `package.json` to an older version.
- Run `vtex-test` - the first one shouldn't block the execution.
- Run `vtex-test` again, it now should block the execution.

Create outdated checker

---

CHANGELOG.md
src/lib/error/ErrorReport.ts
src/lib/utils/__snapshots__/truncateAndSanitizeStringsFromObject.test.ts.snap
src/lib/utils/truncateAndSanitizeStringsFromObject.test.ts
src/lib/utils/truncateAndSanitizeStringsFromObject.ts

Sanitize jwt tokens before sending to telemetry 
```
git checkout fix/telemetry-sanitize-tokens
yarn watch
```
Run `vtex-test workspace reset` on master.
It will give an error and an ErrorID
Check the errorId on splunk and check the authorization key - it should have the format:
```
Bearer aaaaaa.bbbbb
```
You can go to jwt.io to check it

Sanitize jwt tokens

---

CHANGELOG.md
src/lib/utils/__snapshots__/truncateAndSanitizeStringsFromObject.test.ts.snap
src/lib/utils/truncateAndSanitizeStringsFromObject.test.ts
src/lib/utils/truncateAndSanitizeStringsFromObject.ts

Buffers will now be serialized as `{byteLength: 123, type: "buffer"}` instead of a giant array of bytes.
```
git checkout fix/sanitize-buffers
yarn watch
```
- Disconnect from internet
- Run `vtex-test workspace reset` to trigger an error
- Telemetry will try to report the error by sending a buffer to the backend - this operation will fail
- Reconnect to internet
- Run `vtex-test workspace reset` when on master to trigger an error and a flush
- After some time check splunk for the error with buffer:
```
index=io_vtex_logs app=vtex.toolbelt-telemetry@* data.errorDetails.requestConfig.data.byteLength!=NULL
```

Simplify buffer serialization on error reports

---

CHANGELOG.md
package.json
yarn.lock

Update plugin for space separated commands. The new version of this plugin fix the alias documentation for subcommand alias that before where still being displayed with `:`.
Fix minor issue in help documentation.
With the beta version released, try `vtex workspace list --help` and see if the `ALIASES` field display the alias with space instead of `:`.

Update space separated commands plugin

---

CHANGELOG.md
src/clients/Tester.ts
src/modules/apps/e2e/report/completedApps.tsx
src/modules/apps/e2e/report/failedApps.tsx
src/modules/apps/e2e/report/index.tsx

tester-hub was updated, changing the way the test results assets are accessed by the user. So the toolbelt `vtex test e2e` must be changed accordingly.
An app with cypress tests must be used, I recommend `shipping-preview`
add `"cypress": "0.x"` builder to its manifest
ensure that there is no   `"video": false` parameter on `cypress.json`
The app must be linked first then you should use the command `vtex tet e2e`
it should appear a working link to the video and screenshot assets at the test results

test e2e Screenshot and video assets updated according to tester-hub

---

CHANGELOG.md
src/commands/config/reset.ts
src/conf.ts
src/modules/config/reset.ts

Create a toolbelt command to reset the config values.
Lack of a way to reset the config values to their default automatically.
In a test workspace, try `vtex-test config reset env` and `vtex-test config reset cluster`. The new value for `cluster` should be ` ` and the new value for `env` should be `prod`.

Create command config reset

---

CHANGELOG.md
src/modules/apps/deprecate.ts
src/modules/apps/undeprecate.ts

The token used by `vtex deprecate` was the one from the previous account (when switching is necessary for deprecating an app) - this was fixed.
Also, telemetry was added on `vtex deprecate` and `vtex undeprecate` errors.
```
git checkout chore/telemetry-undeprecate
yarn watch
```
From an account different than `vtex`, run:
```
vtex-test deprecate vtex.service-example@0.1.0-beta.0
vtex-test undeprecate vtex.service-example@0.1.0-beta.0
```

Fix undeprecate 403. Add telemetry on deprecate and undeprecate

---

CHANGELOG.md
src/modules/workspace/promote.ts

Change evolution manager error report log level from `error` to `debug`

Change evolution manager error report log level

---

CHANGELOG.md
src/modules/apps/publish.ts

To make it clear for the community of VTEX IO developers that their docs are available in vtex.io/docs
Most VTEX IO developers outside VTEX are not aware of this feature. I've aligned with Bia to also announce it in the next Release Notes.
Publish an app with and without docs to see (or not) the message

Add docs location message

---

.eslintignore
CHANGELOG.md
src/commands/workspace/create.ts
src/lib/clients/eventSources/AppLogsEventSource.ts
src/lib/error/ErrorReport.ts
src/lib/session/SessionManager.ts
src/lib/session/WorkspaceCreator.ts
src/lib/session/__mocks__/SessionManager.ts
src/lib/sse/index.ts
src/modules/auth/login.ts
src/modules/auth/switch.ts
src/modules/auth/welcome.ts
src/modules/lighthouse/auditUrl.ts
src/modules/lighthouse/showReports.ts
src/modules/setup/setupTSConfig.ts
src/modules/setup/setupTooling.ts
src/modules/setup/setupTypings.ts
src/modules/support/login.ts
src/modules/workspace/common/edition.ts
src/modules/workspace/create.ts
src/modules/workspace/use.ts
tsconfig.json

- Create workspace if the targetWorkspace doesn't exist when using `vtex switch` or `vtex login` 
- Do not send `CommandError`s (usually misusage errors) to telemetry.
```
yarn global add vtex@2.101.1-beta
```
Test around the commands:
```
vtex login account -w nonExistentWorkspace
vtex login account -w existentWorkspace
vtex switch account -w nonExistentWorkspace
vtex switch account -w existentWorkspace
vtex workspace create nonExistentWorkspace
vtex workspace create existentWorkspace
vtex workspace use existentWorkspace
vtex workspace use nonExistentWorkspace
```

Create workspace when logging in into a non-existent one

---

CHANGELOG.md
src/modules/apps/e2e/index.tsx

Raise the proper error when running `vtex test e2e` on an app that isn't linked. Without this fix, it might be not so clear why the script is breaking. Motivation for this PR: https://github.com/vtex-apps/checkout-io-tests/pull/5#issuecomment-638850876
Before:
After:
1. Clone vtex-apps/checkout-io-tests#5
2. Go to `checkoutio` account on `wdsrocha` workspace
3. Run `yarn e2e:run:remote`

Handle error on unlinked apps when running `vtex test e2e`

---

CHANGELOG.md
package.json
src/lib/clients/IOClients/apps/Builder.ts
src/lib/constants/Headers.ts
src/lib/error/ErrorKinds.ts
yarn.lock

We don't have visibility on when sticky host errors start to happen for IO developers. This PR adds telemetry to it.
Testing the errors scenarios is kinda difficult, so just make sure `vtex link` and relinks are working properly. 
Here are some errors logged on splunk when I was testing the error format:
https://splunk72.vtex.com/en-US/app/vtex_io_apps/search?earliest=1592321400.000&latest=1592321700&q=search%20index%3Dio_vtex_logs%20level%3Derror%20app%3Dvtex.toolbelt-telemetry%40*%20data.kind!%3DNULL%20data.kind!%3DTelemetryReporterError%20data.kind!%3DSSEError%20%20%22data.kind%22%3DStickyHostError&display.page.search.mode=fast&dispatch.sample_ratio=1&display.general.type=events&display.page.search.tab=visualizations&sid=1592322428.1459595_3DDE77BC-1901-4189-B912-ADE751E100F6&workload_p …

Report sticky host errors

---

CHANGELOG.md
src/commands/link.ts
src/modules/apps/link.ts
src/modules/auth/login.ts
src/oclif/hooks/init.ts

Enable a in a single line command, that wraps the `switch, use, link` or `login, link` command
`vtex link -a storecomponents -w savio`

Enabled login on `vtex link`

---

CHANGELOG.md
src/modules/apps/settings/set.ts

A lot of releases ago this command was changed, removing the value cast before setting it to a field. This PR reverts it, since the desired behavior is to cast the value before setting.
```
vtex-test settings set vtex.service-example@0.x boolean false
```
You should see:
```json
{
"fieldName": "fieldValue",
"teste": 1,
"boolean": false
}
```
Instead of:
```
{
"fieldName": "fieldValue",
"teste": 1,
"boolean": "false"
}
```

Fix settings set

---

CHANGELOG.md
src/api/clients/IOClients/external/VTEXID.ts
src/api/session/SessionManager.ts
src/api/session/__mocks__/SessionManager.ts
src/commands/logout.ts
src/modules/auth/logout.ts

Now `vtex logout`:
- Invalidates local token before deleting it.
- Opens URL to invalidate auth cookie stored on browser.

Improve vtex logout

---

CHANGELOG.md
src/api/storeUrl.ts

- Fix addWorkspace option on storeUrl util that affected `vtex browse`
To test check if `vtex browse` opens the url for your account/workspace.

Fix vtex browse not adding workspace to url

---

CHANGELOG.md
package.json
yarn.lock

- Adding the `@vtex/cli-plugin-submit` to the Toolbelt. It adds the `vtex submit` command for submitting apps for App Store review process.
- As we're releasing the new App Store this week, we need the functionality on VTEX Toolbelt, allowing external developers to submit their apps to the homologation process.
- Running `vtex-test submit` on an IO app.

Adding vtex submit plugin

---

CHANGELOG.md
package.json
src/__tests__/utils.test.ts
src/lib/constants/Messages.ts
src/modules/utils.ts
src/update.ts
yarn.lock

`updateNotify` method was not updating correctly `toolbelt` versions based on `channels`
Now `toolbelt` will notify the CLI version update based on his own `channel`

Change version update notifier structure

---

CHANGELOG.md
package.json
src/modules/apps/link.ts

We are experiencing some connectivity issues on the platform [query](https://splunk72.vtex.com/en-US/app/vtex_io_apps/search?q=search%20index%3Dio_vtex_logs%20%7C%20spath%20%22data.parsedInfo.response.data.message%22%20%7C%20search%20%22data.parsedInfo.response.data.message%22%3D%22Connection%20refused%22%7C%20spath%20app%20%7C%20search%20app%3D%22vtex.toolbelt-telemetry*%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&earliest=-3w&latest=now&display.general.type=events&display.page.search.tab=events&display.visualizations.charting.chart=line&sid=1604421610.500111_F40559E7-0C1C-4566-8DBF-B2707C656667)
Add retries to builderhub client to diminish those issues.

Add builderhub client retries for links

---

scripts/install.sh
scripts/uninstall.sh

Change `aws` install script to download `toolbelt` from base tar to custom tar
When `toolbelt` have some version deprecated, the new user that download `toolbelt` from this script will download the latest version that is the deprecated file.

Change Install script download url

---

CHANGELOG.md
package.json
src/api/modules/auth/switch.ts

[Jira card](https://vtex-dev.atlassian.net/browse/DT-360?atlOrigin=eyJpIjoiMWI3MmNiNzNlZmIzNDJmOGI3NDIwNTQ3NzYxMWUwZTYiLCJwIjoiaiJ9)
Don't throw error when switching to same account.
If I use the command:
vtex switch `storecomponents/breno`
And I'm at `storecomponents/foobar`, toolbelt will throw an error saying that I'm already at storecomponents and won't switch me to the workspace breno.
The ideal would be to just to move me to the new workspace.
After the command `yarn watch`, you may try:
```bash
vtex-test switch vtex/master
vtex-test switch vtex/master
vtex-test switch vtex/davi
vtex-test switch storecomponents/master
```

Don't throw error when switching to same account

---

CHANGELOG.md
package.json
src/api/modules/utils.ts

Users could not install apps with `billingOptions` that did not have any `metrics`
1) `vtex-test install acupula.ditocrm`
App's Billing Options should be shown correctly

Fix install's plan message for plans without metrics

---

.github/workflows/create-release-and-trigger-publish.yml
.github/workflows/publish-stable-aws.yml
.github/workflows/publish-stable-npm.yml
CHANGELOG.md

Fix Github Action Deploy
When `github_dispatch` is triggered, it runs on `master`, so won't deploy the latest version that are in the branch, since we can't run `releasy` on master because is protected, this solution will run on the deploy branch.
New workflow
- Merge feture on master
- Create new branch com master with the name of the new version, ie: `v.2.139.0`
- run `releasy patch | minor | major` in order to bum to the version desired ( the same as the branch name)

Add branch name in order to run action in custom branch

---

CHANGELOG.md
src/commands/init.ts
src/modules/init/git.ts
src/modules/init/index.ts

New option to specify folderName when using init command and check for the default branch when downloading template
Fix a bug with the `init` command and improve a bit the experience of using it by enabling the option to specify a folderName for the new project.
This PR is solving a problem where I wasn't able to `init` a new project using the `graphql-example` template because we assumed the default branch for all projects was the `master` branch but I got a 404 cause we're using `main` as the default branch.
This could be tested by cloning the branch, running `yarn watch` on the project and trying the following commands on a new terminal:
```bash
$ vtex-test init --help
$ vtex-test init project1
$ vtex-test init
```
https://user-images.githubusercontent.com/5959178/108906512-bcd33280-75f …

New option to specify folderName when using init command and checking for the default branch when downloading template

---

CHANGELOG.md
package.json
src/api/conf.ts
src/api/modules/utils.ts
src/modules/apps/link.ts
src/modules/apps/publish.ts

[Jira card](https://vtex-dev.atlassian.net/browse/DT-404?atlOrigin=eyJpIjoiNTUwOTY0NWM0ODM4NDI4NGEwYmQ5YmE5Y2YxYWEzZDciLCJwIjoiaiJ9)
We're adding a message with some terms of development while using the react builder
Lack of information about the responsibilities involved in developing a react app
You shall try to link a react app using this version of the toolbelt.
I've done that using the `react-app-template` app, from `vtex init`.
The message that's displayed
The default selection is no:
If you accept, the link will continue as is:
- The message will be displayed only with the linking action
- The app must use the `react` builder at any version
- The message will not be displayed more than two times
- It will wait for 24 hours or until the next day to start to display the message again

DT-404 update react link message

---

CHANGELOG.md
src/modules/setup/setupTypings.ts

Add self (app you are setuping) package to react app dev dependencies
This allows the use of graphql operation types, by importing the app types. Related to https://github.com/vtex/builder-hub/pull/1095
- npm link package
- vtex setup on your app
- check react package devDependecies, it should include self package

feat(react-graphql-types): add self package to react dev dependencies

---

CHANGELOG.md
package.json
src/lib/constants/InstallStatus.ts
src/modules/apps/install.ts
src/typings/global.d.ts

Fix install command
install command was breaking because InstallStatus wasn't being found.
Try to install a few apps.

Treat InstallStatus as a constant instead of a type

---

CHANGELOG.md
package.json
yarn.lock

This adds the command `vtex sfj start` to run a local server of serverless functions.
It adds support for developing serverless functions on the StoreFramework JAMStack. Please check more details in the [Serverless Functions documentation](https://www.notion.so/vtexhandbook/Serverless-Functions-d4fc56c349794a2a8f9cc04daef06677).
On a store with serverless functions, run `vtex sfj start`. You can test it on this store's branch: https://github.com/vtex-sites/storecomponents.store/pull/708.

Add cli-plugin-functions

---

CHANGELOG.md
src/api/modules/sponsor/setEdition.ts
src/api/modules/utils.ts
src/modules/apps/install.ts

This fixes 2 main issues with the `vtex edition set command`:
- We were not handling responses to flow prompts, so we completely ignored when the user said
they didn't want to do some action like confirm the change in the `master` workspace or switching
to the sponsor account.
- This is the more complex one which is almost a feature: to actually handle when the setEdition
API request actually returns a 404 error because of the `vtex.tenant-provisioner` app not being 
installed. Now we handle the corresponding not found errors from router and prompt the user to
already install the necessary app and retry the request after installing.
The 2 tricky parts were:
- The route map of the platform has only eventual consistency, so we don't have guarantee anymore
that after installing an app, a …

Fix edition set command error handling

---

CHANGELOG.md
src/api/modules/utils.ts
src/modules/apps/install.ts

The purpose of this pull request is to handle apps of type `sponsored` as free apps, during the installation process.
After some changes related to billing ([#1019](https://github.com/vtex/toolbelt/pull/1019)), users started to have problems when trying to install an app of type `sponsored` that didn't declare any billing plan. [Here](https://vtex.slack.com/archives/C2WSEU9QQ/p1618942741133300) we have an explanation of the behavior they have observed.

Fix / installation / Handle sponsored apps as if they were free

---

CHANGELOG.md
package.json
yarn.lock

To update @vtex/cli-plugin-plugins to 1.13.0.
Changes in [#8](https://github.com/vtex/cli-plugin-plugins/pull/8) don't work in toolbelt without this.
The feature of @vtex/cli-plugin-plugins@1.13.0 can be tested with the following command: `vtex plugins source`.

Update @vtex/cli-plugin-plugins to 1.13.0

---

CHANGELOG.md
package.json
src/api/modules/utils.ts
src/lib/constants/BillingMessages.ts
src/modules/apps/install.ts
yarn.lock

With the goal ensuring a single source for buying [VTEX App Store](https://apps.vtex.com/) apps, this PR removes the option to buy apps that are available in App Store, including free apps.
Why?
App Store is a VTEX store which mean users can buy apps using the VTEX's checkout experience. As a marketplace, App Store can give more transparency to both buyers and sellers when the process of buying apps is done using VTEX e-commerce features. Feel free to get in touch with App Store team (or Squad 1) to get more details about this!
https://github.com/vtex/billing-app/pull/111 removes app purchases (or App Store contract creation), which means that apps that are in App Store can only be purchased (including free apps) from VTEX App Store [website](https://apps.vtex.com/).
As a consequence, …

Remove app purchases

---

README.md

This request adds a suggestion of windows installer to the README.md file
Windows users might need extra steps if installing it from `yarn` or `npm`, like adding the folder to the Path, so that the command works.
But there already exists a installer that does all the job, it is just not suggested as an installation method. This information is quite useful for those installing it on Windows machines. I'm picking the installer URL as recommended in this [issue](https://github.com/vtex/toolbelt/issues/1111).
No tests, only adding documentation.

adding instructions to install it on windows from an executable file

---

CHANGELOG.md
src/api/modules/workspace/common/edition.ts

There is a warning message that is outdated. It recommends `edition-store@2.x`, when it should recommend `edition-store@5.x` according to this doc:
https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-edition-app
It also shares an outdated vtex.io/docs link to the documentation.
Reducing the confusion in novice developers working with Store Framework
Open an account that had `edition-business@0.x` and try doing `vtex workspace reset`. It should show an updated message, recommending `edition-store@5.x` and the proper documentation link in our Developer Portal.

Update recommendedEdition in edition.ts

---

.github/workflows/create-release-and-trigger-publish.yml
CHANGELOG.md
package.json

Fix the CI/CD workflow that trigger the publishing in `npm` and system-oriented package managers such as `brew`.
The current workflow is broken here
1. Launch a new stable tag with `releasy`;
2. All steps should successfully execute;
None

Fix CI/CD pipelines

---

CHANGELOG.md
src/lib/auth/AuthProviders/OAuthAuthenticator/LoginServer.ts

* handle OPTIONS request for CORS
* https://github.com/vtex/toolbelt/issues/1212
* Running `toolbelt` locally.

chore: handle OPTIONS request for CORS

---

CHANGELOG.md
README.md
docs/maintaining.md

Improve deployment documentation to ensure we're following the correct steps.
Enables developers to clearly understand the process and run it without issues.
N/A
N/A

Add deployment steps

---

CHANGELOG.md
src/api/pinnedDependencies.ts

Change the logic that handles pinned dependencies to allow configs for specific builders to have higher precedence than the common configs.
This won't cause any problems, since the Typescript is currently the only common pinned dep and there are currently no builders trying to change its value either. You can see the current pinned dependencies config [here](https://github.com/vtex/builder-hub/blob/master/node/request/handlers/pinnedDependencies.ts#L15).
With the current logic it's impossible to allow other Typescript versions to be used in any builders. A new node builder major is being created (PR [here](https://github.com/vtex/builder-hub/pull/1184)) to upgrade TS and it needs this change to properly work.
First test the existing use cases:
1. Load the repo of an existing Node.js app. …

Allow specific builder config to override the common config for pinned dependencies

---

.github/workflows/ci.yml
.github/workflows/publish-prerelease-npm.yml
.github/workflows/publish-stable-aws.yml
.github/workflows/publish-stable-npm.yml
CHANGELOG.md
package.json
src/modules/apps/install.ts
src/modules/apps/publish.ts
src/modules/apps/unlink.ts

_note to reviewers_
The commit 1eb25c3 was added because there were some prettier issues, failing the ci tests.
---
Build toolbelt binaries using node current the active LTS version.
Incompatibilities between the toolbelt and its plugins - [XTNSNS-665](https://vtex-dev.atlassian.net/jira/software/c/projects/XTNSNS/boards/876?selectedIssue=XTNSNS-665). This issue affects users that get the toolbelt from brew or windows installer (I guess Linux user might face the same issue, but I didn't test it).
If you want to test it locally, clone the branch and run `yarn release && yarn release:win`. The binaries will be available on `/lib`.
I also tested it by linking an application to ensure there wouldn't be any incompatibility with the nodejs version used by the runtime.
_windows_
_macos_ …

Update node version

---

CHANGELOG.md
src/__tests__/modules/featureFlag/featureFlagDecider.test.ts
src/api/clients/IOClients/apps/ToolbeltConfig.ts
src/api/error/ErrorReport.ts
src/modules/featureFlag/featureFlagDecider.ts

As requested in #1245, the goal of this PR is to display the URL that will be opened in the browser to allow the user to open it manually in case of errors.
Some users using Unix distributions were not able to login using `vtex login` because the `open` and `opn` packages do not work properly in their OSs.
1. Add the `.vtex/dev/bin` folder to the PATH, as mentioned in the CONTRIBUTING file;
2. run `yarn watch` in the root folder of the repository
3. run `vtex-test login`
4. see the url

Showing URL when opening browser

---

.github/workflows/create-release-and-trigger-publish.yml
CHANGELOG.md
package.json

To allow triggering new releases manually. Also, it fixes the Changelog, since a new version was released and the changelog wasn't updated properly.
Currently, when we go to `Releases` and create a new release manually, creating a new tag, the `create-release-and-trigger-publish` workflow fails with the error `Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}`. To fix this issue, we need to skip the `create-release` job when the tag already exists, proceeding to the next step.
-
-

Update deployment to allow manual release
