src/lib/auth.coffee
=> Cria/usa a pasta .vtex na home do user

src/lib/file-manager.coffee
=> Fallback para .gitignore caso não exista .vtexignore

README.md, src/lib/meta.coffee, src/lib/publish.coffee, src/lib/watch.coffee, src/vtex-publish.coffee, src/vtex-watch.coffee
=> Altera nome owner para vendor

package.json, src/lib/watch.coffee, src/vtex-watch.coffee
=> Implement vtex say

src/lib/watch.coffee
=> Remove obsolete files from sandbox

src/lib/watch.coffee
=> Fix livereload for multiple apps

src/lib/watch.coffee
=> Display sandbox warnings

src/lib/auth.coffee
Fix bug when user interrupted (ctrl+c) in the middle of login
=> Fix login interrupt

src/lib/webpack.coffee
Doing this so we may debug #65
=> Add more error messages to ease debugging

package.json, src/lib/watch.coffee
=> Replace websocket with http keep-alive

.travis.yml, create-npmrc.sh
- Use API encrypted key
- Use `sudo: false` for faster deploy
- Use node v4
=> Fix travis deploy

src/lib/file-manager.js
Keep node_modules, .git and package.json out of apps.
=> Add default ignore

src/bin/vtex-watch.js, src/lib/watch.js, src/lib/webpack.js
Fix #111
Fix #70
This PR fixes the sandbox deactivation on SIGINT exit.
Also fixes the output problems on the process of exiting.
=> Fix toolbelt sandbox deactivation on exit

src/conf.js, src/greeting.js, src/modules/workspace.js, src/vbase/VBaseClient.js, src/vbase/index.js, src/vbase/util/required.js
Add 'workspace use' command
Migrate to Vbase
=> Migrate to Vbase

src/render.js
Depends on https://github.com/vtex/gulp-vtex-render/pull/2
=> Change gulp steps to match single route file

.gitattributes, package.json, src/courier.js, src/modules/apps.js
This feature consists of outputting to the console app-related events. Such events can be raised either by the apps server itself, or any other service that relates to it.
=> Logging of app events

CONTRIBUTING.md, README.md, package.json
To update the README and CONTRIBUTING documents to the latest developments.
README had incorrect menu example, CONTRIBUTING lacked git workflow.
n/a
n/a
=> Improve README and CONTRIBUTING for V1

src/courier.js
Uses specific prefix to track workspace change events
Creates a system handler event to receive workspace changes and execute livereload
`vtex watch --verbose` should work. 
N/A
=> Log events to console

src/modules/index.js, src/modules/init.js
Add an `init` command that creates files and folders necessary for a VTEX app.
Friction on creating new apps.
Running `vtex init`.
n/a
=> Add init command

package.json, src/apps.js, src/apps.test.js, src/courier.js, src/modules/apps.js, src/spinner.js, src/time.js
Improve log messages (mostly when not using `--verbose`).
Poor messages when developing an app using the toolbelt.
Just run `vtex watch` on an app directory.
=> Improve log messages

package.json, src/auth.js, src/cli.js, src/file.js, src/file.test.js, src/modules/apps.js, src/modules/auth.js, src/modules/workspace.js
Use new `node-vtex-api` version `0.10`, which changes how apps are published. We are now sending a streaming, gzipped request with content type `multipart/mixed`.
Making things FASTER 💨 
Wait for @ewilazarus to finish the new API support :joy: 
N/A
=> Port to new vtex api

.eslintrc, package.json, src/auth.js, src/clients.js, src/endpoint.js, src/modules/apps/add.js, src/modules/apps/install.js, src/modules/apps/link.js, src/modules/apps/list.js, src/modules/apps/publish.js, src/modules/apps/settings/index.js, src/modules/apps/settings/set.js, src/modules/apps/settings/unset.js, src/modules/apps/uninstall.js, src/modules/apps/unlink.js, src/modules/apps/utils.js, src/modules/apps/watch.js, src/modules/auth/login.js, src/modules/infra/install.js, src/modules/infra/list.js, src/modules/infra/update.js, src/modules/workspace/create.js, src/modules/workspace/delete.js, src/modules/workspace/list.js, src/modules/workspace/promote.js, src/modules/workspace/use.js, yarn-error.log, yarn.lock
To upgrade the `@vtex/api` package to its newest version.
Standardizing client usage.
By running every command and testing different scenarios. I have already tested many of them.
=> Switches to new context-bound clients

package.json, src/modules/index.ts, src/modules/io/index.ts, src/modules/io/install.ts, src/modules/io/list.ts, src/modules/io/utils.ts, typings.d.ts, yarn.lock
Implement io list/install commands
- run `vtex io ls` to see what is the versions of IO that is currently installed on the account/workspace
- run `vtex io ls -a` to see all available versions
- run `vtex io install {version}` to install the version on the current account/workspace
=> Implement io list/install commands

src/modules/apps/link.ts
Give feedback when finished sending files
Help to identify timeouts problems
=> Give feedback when finished sending files

src/modules/workspace/promote.ts
Before starting the promotion of a workspace, we must ensure we are not trying to promote master to master. This PR implements this.
It does not make sense to promote master to master, so this operation should not be allowed.
1) Try to promote master workspace. See it fail.
2) Try to promote another workspace. See it work.
```
~$ vtex workspace
? Workspaces: master
~$ vtex workspace promote --verbose
15:46:51.437 - debug:   Promoting workspace master
15:46:51.453 - error:   It is not possible to promote workspace master to master
~$ vtex workspace
? Workspaces: igor
~$ vtex workspace promote --verbose
15:47:11.788 - debug:   Promoting workspace igor
? Are you sure you want to promote workspace igor to master? No
```
=> Do not allow promotion if user is in workspace master

CHANGELOG.md, src/modules/apps/list.ts, src/modules/tree.ts
Adds a `--short` or `-s` option to the `list` command
=> ls --short

package.json
Do a simple check on the expiration of local token when using the cli.
Saves people some time since the local token will always be valid (if it is not valid, it will immediately prompt for login).
Run 'vtex local token' with an expired token configured.
=> Release v2.36.1

package.json, src/modules/apps/link.ts
=> Remove builder hub from legacy link if

package.json, src/cli.ts, src/modules/apps/link.ts, src/modules/apps/publish.ts, yarn.lock
=> Retry and log when builder-hub returns errors for link and publish routes

package.json, src/clients.ts, src/modules/apps/legacyLink.ts, yarn.lock
Update @vtex/api to latest version
=> Use @vtex/api@1.8.1

package.json, src/modules/apps/link.ts, src/modules/apps/publish.ts
Fix retries for `link` and `publish` implemented in #476 .
=> Fix retries

CHANGELOG.md, package.json
This commit fixed the Changelog format and attributes some feature entries to their right version tags.
=> Fix Changelog

CHANGELOG.md, package.json, src/modules/auth/login.ts, src/sse.ts
This PR uses the new routes of auth-server
=> Adding new routes to auth-server

CHANGELOG.md, package.json, scripts/closeChrome.scpt, src/modules/auth/login.ts, src/sse.ts
Add script to close Chrome tab that was successful on login. Only works on mac.
Tab that is left open on mac is annoying.
?
=> Close chrome tab on mac after successful login

CHANGELOG.md, package.json, src/modules/release/index.ts
This PR adds hkignore as prerelease flag, since it's a new flag supported by Apps
=> Adds hkignore as prerelease flag

CHANGELOG.md, package.json, src/modules/release/index.ts
This PR makes possible to run `vtex release pre` as `vtex release prerelease`
=> Adds pre as prerelease

CHANGELOG.md, package.json, src/modules/apps/list.ts
This PR proposes changes to the formatting of linked apps in the result of the `vtex ls` command.
=> Change linked apps formatting in vtex ls

CHANGELOG.md, package.json, src/modules/deps/diff.ts, src/modules/deps/utils.ts, src/modules/tree.ts, yarn.lock
This command shows a diff of dependencies between the first and second arguments.
Usage is `vtex deps diff <workspace1>(optional) <workspace2>(optional)`.
Default value for `workspace1` is `'master'`. Default value for `workspace2` is `{current workspace}`.
=> Implement vtex deps diff command

CHANGELOG.md, package.json
=> Update changelog and bump version

CHANGELOG.md, package.json, src/modules/workspace/reset.ts, src/modules/workspace/use.ts
Fix flag that was not being set correctly in `vtex use` command.
Try `vtex use <workspace> -r` and `vtex use <workspace> -rp` and make sure both work as expected.
=> Fix bug when resetting workspace through use command

CHANGELOG.md, package.json, src/cli.ts
=> Print entire unhandled errors when run with --verbose

CHANGELOG.md, package.json, src/modules/init/index.ts
This PR adds [service example](https://github.com/vtex-apps/service-example) to the `vtex init` command.
=> Add service-example to the init command

CHANGELOG.md, package.json, src/clients.ts, src/modules/init/index.ts
=> Add delivery-theme to vtex init

CHANGELOG.md, package.json, yarn.lock
This updates `@vtex/api` to version `^3.3.1`, which fixes the builder availability bug.
=> Update @vtex/api version

CHANGELOG.md, package.json, src/modules/tree.ts, src/modules/workspace/production.ts
As the title says, remove the deprecated command `vtex production`.
=> Remove the vtex production command

CHANGELOG.md, package.json, src/clients/index.ts, yarn.lock
=> Upgrade @vtex/api to 3.4.0 or higher

CHANGELOG.md, package.json, src/modules/workspace/abtest/finish.ts, src/modules/workspace/abtest/status.ts
Minor fixes to A/B test `finish` command.
=> Yet another fix to A/B test finishing messages

CHANGELOG.md, package.json, src/cli.ts, src/clients/abTester.ts, src/clients/sponsor.ts, src/modules/apps/publish.ts, src/modules/sponsor/getEdition.ts, src/modules/sponsor/setEdition.ts, src/modules/sponsor/utils.ts, src/modules/tree.ts, src/modules/utils.ts, src/modules/workspace/abtest/status.ts, yarn.lock
Implements new commands for sponsor account functionality:
- `vtex edition`: gets the edition of the current account.
- `vtex edition set {edition@version}`: sets the edition of the current account. 
Use account `vtexgame42` and edition `vtexgame43.edition-test@0.x`.
=> Sponsor Account

CHANGELOG.md, package.json, src/modules/apps/list.ts
=> Make vtex ls show apps inherited by account's edition

CHANGELOG.md, package.json, src/modules/init/index.ts
=> Adds admin app example

CHANGELOG.md, package.json, src/modules/init/index.ts
Adds graphql example for hackathon vtex
=> adds graphql example

CHANGELOG.md, package.json, src/modules/release/utils.ts
=> Fix vtex release cwd for scripts in manifest.json

CHANGELOG.md, package.json, src/modules/apps/link.ts, src/modules/utils.ts
Rewrite pinned dependency versions on `package.json`
Follow up to https://github.com/vtex/builder-hub/pull/589
=> Enforce pinned dependencies

CHANGELOG.md, README.md, src/cli.ts, src/conf.ts, src/env.ts, src/modules/apps/publish.ts, src/modules/auth/login.ts, src/modules/tree.ts
Staging is new deprecated and should be removed from Toolbelt
There's dead code from the deprecated staging environment that must be removed
Just see if things keep working
=> Remove staging environment from Toolbelt

plugins/fish/fish_prompt.fish
Staging is dead, so showing the env doesn't make sense anymore
=> Change fish prompt to not show env

src/greeting.ts
Saying `prod` on greeting string doesn't make sense now that it's the only available environment
=> Remove env from greeting

CHANGELOG.md, package.json, src/modules/workspace/abtest/status.ts
Fix a typo and a wrong use of `ComparisonTable`.
=> Fix A/B Testing Status

CHANGELOG.md, package.json, src/modules/housekeeper/update.ts
Correctly show when there are no available updates.
=> Fix `vtex update`

CHANGELOG.md, package.json, src/modules/workspace/create.ts
This reverts commit 47ef1df2e678fdc19a15db24973e2f853dd649ab.
=> Revert "Remove request to builder-hub when a new workspace is created"

CHANGELOG.md, package.json, src/sse.ts
Fix exploding on link
By linking any project with it, wait for empty colossus log and see that it doesn't break
=> Fix filterAndMaybeLogVTEXLogs

CHANGELOG.md, package.json
Bump version and Fix CHANGELOG.
=> Bump version and fix CHANGELOG

CHANGELOG.md, README.md, package.json
=> Add `vtex redirects` to README

CHANGELOG.md, package.json, src/update.ts, yarn.lock
When there's an update, toolbelt shows a box giving instructions on how to update using npm. Like this:
This PR give instructions using yarn, if the user has it installed.
=> Update notifier now show yarn command

.travis.yml, CHANGELOG.md, package.json
Some dependencies started to use features introduced on later node versions
=> Enforce node version >= 10

CHANGELOG.md, package.json, src/clients/index.ts, src/modules/apps/file.ts, src/modules/apps/link.ts, src/modules/apps/test.ts, src/modules/deps/diff.ts, src/modules/tree.ts, src/modules/utils.ts, src/modules/workspace/abtest/utils.ts, yarn.lock
Add support for running tests on VTEX IO apps with the `vtex test` command.
This PR depends on these ones:
https://github.com/vtex/builder-hub/pull/675
https://github.com/vtex/node-vtex-api/pull/218
=> Support for running tests on VTEX IO apps

CHANGELOG.md, README.md, package.json, src/modules/tree.ts, yarn.lock
=> Add `vtex test` to README

CHANGELOG.md, package.json, src/clients/rewriter.ts, src/modules/rewriter/delete.ts, src/modules/rewriter/export.ts, src/modules/rewriter/import.ts, src/modules/rewriter/utils.ts
This PR makes adjustments to the usage of `vtex.rewriter` (redirects manager), conforming to the changes in API from vtex/rewriter#35.
=> Account for index sharding in vtex.rewriter

CHANGELOG.md, package.json
=> Release v2.77.0

CHANGELOG.md, package.json, src/modules/apps/file.ts, src/modules/deps/utils.ts, src/modules/workspace/abtest/finish.ts, src/modules/workspace/abtest/start.ts, yarn.lock
Update typescript version. New packages added tend to use new typescript features on its types and with older tsc versions we can't use these types.
=> Update typescript version

CHANGELOG.md, package.json, src/modules/support/login.ts, yarn.lock
Remove `inquirer` from dependencies. `enquirer` package, which is installed, has the same purpose
=> Remove inquirer

CHANGELOG.md, package.json, src/modules/apps/file.ts
Prevents watching .git folder
Avoids this:
=> Ignore .git folder by default

CHANGELOG.md, package.json, src/__tests__/modules/setup/setupESLint.test.ts, src/modules/setup/setupESLint.ts
=> Update vtex setup lintDeps

CHANGELOG.md, src/modules/apps/install.ts, src/modules/apps/uninstall.ts
```
git checkout  refactor/install-uninstall && \
```
```
// One app install and uninstall
vtex install vtex.service-example@0.x
vtex ls | grep vtex.service-example 
vtex uninstall vtex.service-example@0.x
vtex ls | grep vtex.service-example 
// Local project install and uninstall - Go to a project with a manifest
git clone https://github.com/vtex-apps/checkout-summary.git && cd checkout-summary
vtex install
vtex ls | grep vtex.checkout-summary 
vtex uninstall
vtex ls | grep vtex.checkout-summary 
// Many app install and uninstall
vtex uninstall vtex.service-example@0.x vtex.checkout-summary@0.x
vtex ls | grep vtex.service-example
vtex ls | grep vtex.checkout-summary …
```
=> Refactor `vtex install` and `vtex uninstall`

CHANGELOG.md, package.json
=> Release v2.83.0

CHANGELOG.md, package.json, src/lib/manifest/ManifestEditor.ts, src/manifest.ts, src/modules/apps/add.ts, src/modules/apps/utils.ts, yarn.lock
Install this toolbelt branch:
```
git checkout refactor/add && \
```
Go to an app and try some of the following combinations and check the `manifest.json`
```
vtex add infra:apps vtex.checkout-graphql
vtex add vtex.render-server@7.x
```
=> Refactor `vtex add`

CHANGELOG.md, src/lib/files/YarnFilesManager.ts
```
git checkout fix/relink-issue && \
```
Link an app then change a file - check if the new behavior is updated.
=> Fix relink not properly updating active link

CHANGELOG.md, src/modules/apps/link.ts
=> Fix bad_toolbelt_version error message

src/conf.ts, src/modules/apps/install.ts, src/modules/apps/link.ts, src/modules/apps/testCommand.ts, src/modules/apps/utils.ts, src/modules/config/get.ts, src/modules/housekeeper/update.ts, src/modules/init/index.ts, src/modules/release/utils.ts
```
cd /tmp && \
git checkout chore/fix-eslint-errors && \
```
Test the commands around
=> Fix eslint errors

CHANGELOG.md, src/modules/apps/publish.ts
The announcement has been there already for 1month.
```
cd /tmp && \
git checkout chore/remove-publish-announcement && \
```
Try publishing a app.
=> Remove new deployment process announcement

CHANGELOG.md, package.json, src/modules/apps/deploy.ts, tsconfig.json
Improve and fix deploy messages.
- Print newline before prompting confirmation for going back to original account, avoiding the last message to be overwritten.
- Improve deploy error messages.
```
cd /tmp && \
git checkout chore/use-github-actions && \
```
=> Fix deploy messages

CHANGELOG.md, src/cli.ts, src/modules/apps/deploy.ts, src/modules/apps/deprecate.ts, src/modules/apps/file.ts, src/modules/apps/settings/index.ts, src/modules/apps/settings/set.ts, src/modules/apps/settings/unset.ts, src/modules/apps/undeprecate.ts, src/modules/auth/login.ts, src/modules/infra/install.ts, src/modules/infra/list.ts, src/modules/infra/update.ts, src/modules/workspace/delete.ts, src/modules/workspace/promote.ts, src/modules/workspace/reset.ts, src/modules/workspace/use.ts
This is part of an effort to remove `bluebird` from toolbelt.
```
git checkout chore/partially-remove-bluebird && \
```
- Test the commands `vtex infra install`, `vtex infra update`:
```
vtex infra list
vtex infra install apps@0.46.0
vtex infra list
vtex infra install apps@0.47.0-statevent
```
```
vtex infra install apps@0.46.0
vtex infra list
vtex infra update
vtex infra list
```
- Test the subcommands `vtex settings`
```
vtex switch storecomponents
vtex use napoli
vtex settings storecomponents.test-unitary-tests2
vtex settings set storecomponents.test-unitary-tests2 wololo 123
vtex settings storecomponents.test-unitary-tests2
vtex settings …
```
=> Partially remove bluebird

CHANGELOG.md, src/clients/Builder.ts, src/modules/setup/setupTSConfig.ts, src/modules/setup/setupTypings.ts
```
git checkout chore/partially-remove-bluebird && \
```
=> Increase TSConfig getting timeout

CHANGELOG.md, package.json, src/modules/auth/login.ts, yarn.lock
Add releases notification to improve our release notes reachability.
```
git checkout chore/releases-notification && \
```
=> Add releases notification

CHANGELOG.md, nodemon.json, package.json, scripts/symlink.sh, src/modules/apps/publish.ts, src/modules/build.ts
```
git checkout fix/publish-unhandled-exception && \
```
Add an error on an app so that its publish will fail.
Try publishing it.
=> Fix unhandled exception when publish fails

CHANGELOG.md, src/modules/setup/consts.ts
- Update the package version of our eslint packages
- Use `vtex-react/io` preset instead of `vtex-react` for react IO apps
=> Update eslint pkg version

CHANGELOG.md, src/modules/auth/login.ts
=> Fix release notes URL

CHANGELOG.md, package.json
Bump version 2.91.0
**Fixed**
- Release notes URL.
**Changed**
- [vtex init] Keep only store template for non VTEX users and change template repository.
- [vtex init] Allow to select template organization.
=> Release v2.91.0

CHANGELOG.md, src/modules/auth/login.ts
=> Update release notes URL and month

CHANGELOG.md, package.json, src/clients/rewriter.ts, src/modules/rewriter/export.ts, src/modules/rewriter/import.ts, yarn.lock
Updates redirects export command to new Rewriter API
Depends on: https://github.com/vtex/rewriter/pull/86
Currently rewriter's list API has some problems regarding VBase concurrency, this makes the response not correct. This PR will use the correct API to list the redirects.
=> Updates redirect export

CHANGELOG.md, src/clients/rewriter.ts, src/modules/rewriter/export.ts, src/modules/rewriter/utils.ts
Also download the binding when exporting a redirect
We currently do not download the binding of a redirect, this fixes this problem
=> Pick bindings

CHANGELOG.md, src/CLIPreChecker/DeprecationChecker/DeprecationCheckerStore.ts, src/modules/rewriter/utils.ts
=> Logs exact uri that has a problem

CHANGELOG.md, package.json, yarn.lock
Update open to 7.0.3
Login problem in WSL
=> Fix update open

.eslintrc, CHANGELOG.md, src/cli.ts, src/lib/utils.ts
Add time to init as a metric for toolbelt telemetry.
Lack of visibility in latency to initialize.
=> Add init time metric

CHANGELOG.md, src/lib/error/ErrorReport.ts
Increase object serialization depth.
```
git checkout fix/telemetry-serialization && \
```
Force an API error to occur - check the error on splunk
=> Fix telemetry serialization

CHANGELOG.md, src/modules/auth/login.ts
=> Update RN link

CHANGELOG.md, src/clients/billingClient.ts
Update billing client to new format.
```
git checkout fix/clients-urls
yarn watch
```
Try installing apps on a workspace.
=> Use new URL format on Billing client

src/modules/apps/e2e/report/failedApps.tsx
This will allow for opening the URLs by clicking in the terminal
=> Add missing https protocol on e2e logged URLs

CHANGELOG.md, src/modules/workspace/common/edition.ts
This error doesn't change the user flow, so it would be better to be a debug level.
=> Change edition check error level

CHANGELOG.md, src/modules/apps/link.ts
Context is the same as https://github.com/vtex/builder-hub/pull/1024
=> Watch cypress.json file on link

CHANGELOG.md, bin/run
Some scripts was calling ocllif commmands unnecessarily
=> fix import oclif calls

src/modules/workspace/promote.ts
Change spinner to fix error messages visualization
Running promote in master workspace or in a non production workspace
=> Change spinner to fix error messages visualization

docs/commands.md
There are two alternatives:
- Topic separated files
- All commands in a single file
=> Create commands docs

README.md, docs/commands.md
We are changing the way the Toolbelt communicates with its' users. Changes at the info and messages, visual feedback improvement and more moves to build a tool that ensures users know what they are doing without much effort from them. Rationals and details available [here]( https://www.notion.so/Toolbelt-Styleguide-1943920c5cb84d4a9e22a501c43beab2).
Changing the README to follow the new communication patterns: being more instructive, explaining why the instructions are important more than describing things. 
It also adds a form for users to send us feedback about their experience. 
README was outdated and did not follow our new guidelines.
This should be read-only. I believe that Github is a good tool for discussing the "how to communicate via README" ideas.
=> Rethinking Toolbelts' README

CHANGELOG.md, package.json, yarn.lock
Update plugin `submit` to its latest version
=> Update submit plugin version

CHANGELOG.md, package.json, yarn.lock
Update command plugin submit version
=> Update command plugin submit version

CHANGELOG.md, package.json, src/modules/setup/consts.ts
Guarantee latest versions of our toolings (mainly prettier v2 which was a major change)
Outdated `vtex setup --tooling` environments.
`vtex setup --tooling`
n/a
=> Update tooling deps for setup command

CHANGELOG.md, package.json, yarn.lock
_####_ What is the purpose of this pull request?
=> Upgrade @vtex/cli-plugin-workspace

CHANGELOG.md, package.json, yarn.lock
Bumps the `submit` plugin in order to apply changes made here: https://github.com/vtex/cli-plugin-submit/pull/9
Allows VTEX first party app teams to submit apps to the App Store from any vtex-prefixed account.
=> Bump submit plugin

CHANGELOG.md, package.json, src/CLIPreTasks/DeprecationChecker/DeprecationChecker.ts, src/CLIPreTasks/OutdatedChecker/OutdatedChecker.ts, src/lib/constants/Messages.ts, src/update.ts
Custom messages of `update` `deprecated` and `outdated`
Show personalised message based on user OS
=> Add custom messages

.github/workflows/publish-stable-aws.yml
Deploy on `aws` and bum `brew` formula automatically
=> Add aws github action

.github/workflows/publish-stable-aws.yml
=> fix 'uses' and concat 'run' on Deploy on AWS

.github/workflows/publish-stable-aws.yml
Enable `aws-publish`  to publish `windows` version
=> Add makensis to work windows release

.github/workflows/create-release-and-trigger-publish.yml, .github/workflows/publish-stable-aws.yml, .github/workflows/publish-stable-npm.yml
This Changes were already merged in `3.x` branch
=> Add new action files

CHANGELOG.md, package.json
=> Release v2.121.4

CHANGELOG.md, src/api/modules/workspace/create.ts
Increase workspaces client timeout to 25 seconds
Attempt to workaround this error
=> Increase workspaces client timeout

CHANGELOG.md, src/api/modules/workspace/create.ts
Change 25ms to 25000ms 
Should be 25 seconds not ms
=> Fix 25ms to 25000ms

.github/workflows/stale.yml, CHANGELOG.md
To keep track of relevant github issues in this repo.
Very old issues makes it difficult to see what is really relevant.
Let's see it in action.
=> Add stale issues workflow

.github/workflows/stale.yml, CHANGELOG.md
=> Add stale issue workflow

CHANGELOG.md, CODEOWNERS
=> Add composable commerce as codeowners

CHANGELOG.md, package.json, yarn.lock
Bump `cli-plugin-plugins` to latest version.
Disallowing users to install plugins that won't work.
`vtex-test plugins install @oclif/plugin-help` for example
=> Bump plugin plugins version

src/api/oclif/CustomCommand.ts, src/commands/browse.ts, src/commands/deprecate.ts, src/commands/init.ts, src/commands/install.ts, src/commands/link.ts, src/commands/list.ts, src/commands/local/token.ts, src/commands/login.ts, src/commands/logout.ts, src/commands/publish.ts, src/commands/release.ts, src/commands/setup.ts, src/commands/switch.ts, src/commands/undeprecate.ts, src/commands/uninstall.ts, src/commands/unlink.ts, src/commands/update.ts
_Update descriptions of Toolbelt's default commands._
=> Update command descriptions

CHANGELOG.md, CODEOWNERS
=> Add composable-commerce-sq4 to codeowners and remove composable-commerce

.gitignore, CHANGELOG.md, src/modules/setup/setupTypings.ts
The same as https://github.com/vtex/toolbelt/pull/1036, but for version 3.x
=> feat(react-graphql-types): add self package to react dev dependencies

src/api/clients/eventSources/AppLogsEventSource.ts
Updating logging endpoint protocol
=> Update the logging endpoint

CHANGELOG.md, src/api/clients/eventSources/AppLogsEventSource.ts
Same as https://github.com/vtex/toolbelt/pull/1046
=> Change protocol of logging to https

CHANGELOG.md, CODEOWNERS
=> Add composable-commerce-sq4 as codeowners

CHANGELOG.md, package.json, src/api/conf.ts, src/api/constants/Messages.ts, src/api/modules/utils.ts, src/modules/apps/link.ts, src/modules/apps/publish.ts
=> Prompt for accepting react development terms of use

CHANGELOG.md, package.json
=> Release v2.125.1

CHANGELOG.md, package.json, src/oclif/hooks/utils.ts
=> Update imports to not look at package

CHANGELOG.md, package.json, yarn.lock
=> Update autoupdate dep

CHANGELOG.md, package.json, yarn.lock
=> Update plugin-abtest version

CHANGELOG.md, package.json
=> Release v2.125.3

CHANGELOG.md, package.json, src/modules/init/index.ts
Do a `vtex-test init` and choose service-worker-example. The repo should be downloaded correctly.
=> Add service worker example to list of boilerplates

CHANGELOG.md, package.json
=> Release v2.126.0

CHANGELOG.md, package.json
=> Release v2.127.0

CHANGELOG.md, package.json, src/api/modules/sponsor/setEdition.ts, src/api/modules/utils.ts, src/modules/apps/install.ts
Same as https://github.com/vtex/toolbelt/pull/1068
Literally just a `git cherry-pick` of the squashed commit that went to `master`.
=> [3.x] Fix edition set command error handling

CHANGELOG.md, package.json, src/update.ts
Improve the "new version available" message by 
1. fixing a typo `avaible -> available`;
2. reorganizing the sentence in a way that it seems more natural for native English speakers.
=> [3.x] Fix / Enhance update message

CHANGELOG.md, package.json, src/api/clients/IOClients/apps/Billing.ts, src/api/modules/utils.ts, src/lib/constants/BillingMessages.ts, src/lib/constants/InstallStatus.ts, src/modules/apps/install.ts
Duplicate of https://github.com/vtex/toolbelt/pull/1091, but as a proposal to v3.x
=> Remove app purchases 3.x

CHANGELOG.md, package.json
* add CHANGELOG
* Release v3.0.0
=> Release major 3.x as stable (#1130)

.github/workflows/publish-stable-aws.yml, CHANGELOG.md
* Fixing `publish-stable-aws` pipeline.
* Fixing broken pipeline
=> fix: update publish stable AWS pipeline

.github/workflows/publish-stable-aws.yml
=> fix: update GITHUB_TOKEN in homebrew pipeline

package.json
=> Release v4.2.0
